#!/bin/bash
# stage_sdk.sh — assemble the Nano effect SDK: everything needed to build an
# effect bundle OUTSIDE this repo, and nothing that reaches back into it.
#
#   <out>/VERSION                  ABI version (module_api.h) + repo revision
#   <out>/include/                 module_api.h, gpu.h, host.h, ... + the three
#                                  pre-built helper shader headers
#   <out>/shaders/common/          the shared HLSL includes (nano_*.hlsl)
#   <out>/scripts/                 wasm_build_env.sh (relocatable) + helpers
#   <out>/template/                a forkable one-effect bundle (see its README)
#   <out>/EFFECTS_STYLE_GUIDE.md   the schema conventions the editor relies on
#
# Usage: native/sdk/stage_sdk.sh [out_dir] [--zip]
#   out_dir defaults to <repo>/build/sdk; --zip also writes <out_dir>.zip.
#
# Needs a bundle build to have run first (build_all.sh or `cd core && ./build.sh`)
# for the generated helper headers in native/build/tmp.
#
# FAILS if a header in the SDK #includes a project header that isn't in the SDK
# — the one way an SDK that builds here can fail to build anywhere else.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
native="$(cd "$here/.." && pwd)"
repo="$(cd "$native/.." && pwd)"
wm="$native/wasm_modules"
gen="$native/build/tmp"

out="$repo/build/sdk"
zip=0
for a in "$@"; do
  case "$a" in
    --zip) zip=1 ;;
    *) out="$a" ;;
  esac
done

rm -rf "$out"
mkdir -p "$out/include" "$out/shaders/common" "$out/scripts" "$out/template"

cp "$wm"/include/*.h "$out/include/"
# Helper toolboxes in include/ (effect_blur.h, effect_fast_blur.h, overlay.h)
# #include shader headers a bundle build generates. Ship them pre-built.
for h in blur_shaders.h fast_blur_shaders.h overlay_shaders.h; do
  if [ ! -f "$gen/$h" ]; then
    echo "error: $gen/$h missing — run native/wasm_modules/build_all.sh first" >&2
    exit 1
  fi
  cp "$gen/$h" "$out/include/"
done

cp "$wm"/shaders_common/*.hlsl "$out/shaders/common/"
cp "$wm/wasm_build_env.sh" "$wm/_emit_spv_header.py" "$wm/_fragment_strip.py" "$out/scripts/"
cp "$repo/EFFECTS_STYLE_GUIDE.md" "$out/"

# The template, minus anything a local build of it left behind.
cp -R "$here/template/." "$out/template/"
rm -rf "$out/template/out"

abi="$(sed -n 's/^#define NANO_ABI_VERSION \([0-9][0-9]*\).*/\1/p' "$wm/include/module_api.h")"
rev="$(cd "$repo" && (jj log -r @- --no-graph -T 'commit_id.short()' 2>/dev/null || git rev-parse --short HEAD 2>/dev/null || echo unknown))"
printf 'nano-effect-sdk\nabi %s\nrevision %s\n' "$abi" "$rev" > "$out/VERSION"

# --- Closure check -----------------------------------------------------------
# Every #include in the SDK's headers and template sources must be either a
# system/toolchain header or a file IN the SDK. "Project header" = any header
# name that exists somewhere in this repo's native tree.
project_headers="$(cd "$native" && find src wasm_modules build/tmp -name '*.h' 2>/dev/null \
  | sed 's|.*/||' | sort -u)"
sdk_headers="$(cd "$out" && find include template -name '*.h' | sed 's|.*/||' | sort -u)"
missing=""
while IFS= read -r line; do
  file="${line%%:*}"
  inc="$(echo "$line" | sed -E 's/.*#include[[:space:]]*[<"]([^>"]+)[>"].*/\1/')"
  base="${inc##*/}"
  # Generated by the template's own build, not shipped.
  case "$base" in *_shaders.h) [ "${file#*template/}" != "$file" ] && continue ;; esac
  if echo "$project_headers" | grep -qx "$base" && ! echo "$sdk_headers" | grep -qx "$base"; then
    missing="$missing\n  $file: #include $inc"
  elif [ "$inc" != "$base" ] && echo "$project_headers" | grep -qx "$base"; then
    # A path-qualified project include (<sketch/x.h>) resolves against the
    # repo's src/, which the SDK doesn't have.
    missing="$missing\n  $file: #include $inc"
  fi
done < <(cd "$out" && grep -rnE '^[[:space:]]*#[[:space:]]*include' include template \
           --include='*.h' --include='*.cpp' | sed 's/:[0-9]*:/:/')
if [ -n "$missing" ]; then
  echo "error: the SDK reaches outside itself:" >&2
  printf "$missing\n" >&2
  exit 1
fi

echo "staged SDK (abi $abi): $out"
if [ "$zip" = 1 ]; then
  rm -f "$out.zip"
  (cd "$(dirname "$out")" && zip -qr "$(basename "$out").zip" "$(basename "$out")")
  echo "zipped: $out.zip"
fi
