#!/usr/bin/env python3
"""gen_barrel_effects.py — generate the NanoBarrel native effect registration.

Reads barrel_manifest.txt (the source of truth for which effects the barrel
exposes) and emits, into build/tmp/:

  <namespace>_msl.h       per effect that declares shaders: the SPV->MSL
                          translation (via spirv-cross) of each shader variant,
                          as `static const char <NS>_<VARIANT>_MSL[] = R"(...)";`

  barrel_effects.gen.h    namespace forward-decls for every listed effect +
                          `nano_barrel_gen::registerAllBarrelEffects(rt, registry)`,
                          which (per effect, interleaved) registers the effect's
                          shader MSL then registers the effect. Interleaving is
                          what lets effects share bare shader names like
                          "compute"/"pixel": each effect's PSO is compiled from
                          its own MSL during module_init (synchronous inside
                          registerEffect) before the next effect overwrites the
                          global MSL-name slot.

Inputs: the .spv files the WASM bundle build emitted under build/tmp/. Fails
loudly if a referenced .spv is missing (run the bundle's build.sh first).

Usage: gen_barrel_effects.py <manifest> <tmp_dir>
"""

import os
import subprocess
import sys


def parse_manifest(path):
    effects = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            cols = [c.strip() for c in line.split("|")]
            if len(cols) < 6:
                sys.exit(f"gen_barrel_effects: malformed manifest line: {line}")
            _bundle, ns, eid, display, abi, shaders = cols[:6]
            # Optional 7th column: the literal `identity` flags an effect
            # that exposes an is_identity() predicate the executor can use
            # to skip its dispatch.
            identity = len(cols) >= 7 and cols[6] == "identity"
            shader_pairs = []
            for tok in (s.strip() for s in shaders.split(",")):
                if not tok:
                    continue
                if "=" in tok:
                    regname, variant = tok.split("=", 1)
                else:
                    regname = variant = tok
                shader_pairs.append((regname.strip(), variant.strip()))
            effects.append({
                "ns": ns, "id": eid, "display": display,
                "abi": abi, "shaders": shader_pairs, "identity": identity,
            })
    return effects


def msl_macro(ns, variant):
    return f"{ns}_{variant}".upper() + "_MSL"


def spirv_cross(spv_path):
    return subprocess.run(
        ["spirv-cross", "--msl", "--msl-version", "20000",
         "--msl-decoration-binding", spv_path],
        check=True, capture_output=True, text=True).stdout


def gen_msl_header(ns, variants, tmp_dir):
    """variants: dict variant -> macro. Emits <ns>_msl.h."""
    header = os.path.join(tmp_dir, f"{ns}_msl.h")
    parts = [
        "/* Auto-generated MSL for the NanoBarrel native build. Do not edit. */",
        "#pragma once", "",
    ]
    for variant, macro in variants.items():
        spv = os.path.join(tmp_dir, f"{ns}_{variant}.spv")
        if not os.path.isfile(spv):
            sys.exit(f"gen_barrel_effects: missing {spv} — run the bundle's "
                     f"build.sh (WASM build) first.")
        metal = spirv_cross(spv)
        # Raw string literal — MSL never contains the )NANOMSL" delimiter.
        parts.append(f"static const char {macro}[] = R\"NANOMSL(")
        parts.append(metal.rstrip("\n"))
        parts.append(")NANOMSL\";")
        parts.append("")
    with open(header, "w") as f:
        f.write("\n".join(parts) + "\n")


def cstr(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def gen_registration(effects, tmp_dir):
    L = []
    w = L.append
    w("/* Auto-generated by gen_barrel_effects.py from barrel_manifest.txt.")
    w("   Do not edit — edit the manifest and rebuild. */")
    w("#pragma once")
    w("")
    w('#include "runtime/effect_runtime.h"')
    w('#include "sketch/module_registry.h"')
    w("")
    # Per-namespace MSL headers (only those with shaders).
    for e in effects:
        if e["shaders"]:
            w(f'#include "{e["ns"]}_msl.h"')
    w("")
    # Forward declarations.
    for e in effects:
        ns = e["ns"]
        w(f"namespace {ns} {{")
        if e["abi"] == "instance":
            w("  void  module_init();")
            w("  void* create();")
            w("  void  destroy(void* self);")
            w("  void  init(void* self);")
            w("  void  tick(void* self, double dt);")
            w("  void  render(void* self, int vp_w, int vp_h);")
            w("  void  on_state_patched(void* self, int n, const char* pb,")
            w("                         const int* off, const int* len, const int* ops);")
            if e["identity"]:
                w("  int32_t is_identity(void* self);")
        else:
            w("  void init();")
            w("  void tick(double dt);")
            w("  void render(int vp_w, int vp_h);")
            w("  void on_state_patched(int n, const char* pb, const int* off,")
            w("                        const int* len, const int* ops);")
            if e["identity"]:
                w("  int is_identity();")
        w("}")
    w("")
    w("namespace nano_barrel_gen {")
    w("")
    w("// Registers every manifest effect with the runtime + registry. Shader")
    w("// MSL is registered immediately before each effect so its module_init")
    w("// (run synchronously inside registerEffect) compiles its PSO from its")
    w("// own MSL — effects can therefore share bare shader names.")
    w("inline void registerAllBarrelEffects(effect_runtime::EffectRuntime& rt,")
    w("                                     sketch_executor::ModuleRegistry& registry) {")
    for e in effects:
        ns = e["ns"]
        w(f"  // {e['id']}  ({e['abi']})")
        eid = cstr(e["id"])
        for regname, variant in e["shaders"]:
            # Bare name: consumed synchronously by THIS effect's module_init
            # (createShaderModuleByName) before the next effect overwrites it.
            w(f'  rt.registerShaderMSL("{cstr(regname)}", {msl_macro(ns, variant)});')
            # Module-qualified alias: a STABLE per-effect key. The fusion path
            # compiles its kernel lazily at render time — long after every effect
            # has overwritten the bare names — so it must look the fragment up by
            # "<module_type>::<name>" to get the right effect's fragment (else it
            # fuses with whatever registered the bare name last). See
            # SketchExecutor runFusedGroup.
            w(f'  rt.registerShaderMSL("{eid}::{cstr(regname)}", {msl_macro(ns, variant)});')
        disp = cstr(e["display"])
        if e["abi"] == "instance":
            ident = f", &{ns}::is_identity" if e["identity"] else ""
            w(f'  registry.registerEffect("{eid}", "{disp}",')
            w(f"      &{ns}::module_init, &{ns}::create, &{ns}::destroy, &{ns}::init,")
            w(f"      &{ns}::tick, &{ns}::render, &{ns}::on_state_patched{ident});")
        else:
            # Legacy free-function effect → native trampoline. The old init()
            # (schema + file-static GPU setup) runs once as module_init on the
            # type prototype; per-instance create/init are no-ops; tick/render/
            # on_state_patched forward to the free functions (file-static state,
            # so correct single-instance only).
            ident = (f",\n      [](void* s) -> int32_t "
                     f"{{ (void)s; return {ns}::is_identity(); }}"
                     ) if e["identity"] else ""
            w(f'  registry.registerEffect("{eid}", "{disp}",')
            w(f"      []{{ {ns}::init(); }},")
            w("      []() -> void* { return (void*)1; },")
            w("      [](void*) {},")
            w("      [](void*) {},")
            w(f"      [](void* s, double dt) {{ (void)s; {ns}::tick(dt); }},")
            w(f"      [](void* s, int w, int h) {{ (void)s; {ns}::render(w, h); }},")
            w(f"      [](void* s, int n, const char* pb, const int* o,")
            w(f"         const int* l, const int* op) {{ (void)s; {ns}::on_state_patched(n, pb, o, l, op); }}{ident});")
    w("}")
    w("")
    w("}  // namespace nano_barrel_gen")
    with open(os.path.join(tmp_dir, "barrel_effects.gen.h"), "w") as f:
        f.write("\n".join(L) + "\n")


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_barrel_effects.py <manifest> <tmp_dir>")
    manifest, tmp_dir = sys.argv[1], sys.argv[2]
    effects = parse_manifest(manifest)

    if subprocess.run(["which", "spirv-cross"],
                      capture_output=True).returncode != 0:
        sys.exit("gen_barrel_effects: spirv-cross not found in PATH "
                 "(brew install spirv-cross)")

    for e in effects:
        if not e["shaders"]:
            continue
        variants = {}
        for _regname, variant in e["shaders"]:
            variants.setdefault(variant, msl_macro(e["ns"], variant))
        gen_msl_header(e["ns"], variants, tmp_dir)

    gen_registration(effects, tmp_dir)
    print(f"gen_barrel_effects: {len(effects)} effects → barrel_effects.gen.h")


if __name__ == "__main__":
    main()
