/*
 * example.color.tint — multiply the frame by a colour, by `amount`.
 *
 * The smallest complete effect: a schema (what the editor shows and wires to),
 * one compute shader, and the class-like instance lifecycle —
 *
 *   module_init()   once per effect TYPE: publish the schema, build the PSO.
 *   create()        once per instance (each card in a chain): its own state.
 *   init(self)      after create, with the schema's defaults applied.
 *   on_state_patched(self, ...)   a parameter changed (editor, wire, preset).
 *   render(self, w, h)            draw this frame: tex_in -> tex_out.
 *
 * Copy this folder to start a new effect, rename the namespace and the id, and
 * add it to bundle.cpp and build.sh.
 */

#include <gpu.h>
#include <host.h>
#include "tint_shaders.h"   // generated by build.sh from compute.hlsl

namespace tint {

// Must match `Params` in compute.hlsl, including the float3 + float packing.
struct Params {
  float r, g, b;
  float amount;
};

struct State {
  float r = 1.0f, g = 0.55f, b = 0.2f;
  float amount = 0.5f;
  gpu::Buffer uniforms;
};

static gpu::ComputePSO s_pso;

void module_init() {
  // The id is what sketches store. Give yours a prefix nobody else will use.
  state::init("example.color.tint", {1, 0, 0},
    state::Schema()
      .group("tint", "Tint")
      .rgbField("color", 1.0f, 0.55f, 0.2f, state::PrimaryInput).label("Colour", "Color")
      .floatField("amount", 0.5f, 0.f, 1.f, state::PrimaryInput).label("Amount", "Amount")
      .textureField("tex_in", state::PrimaryInput)
      .textureField("tex_out", state::PrimaryOutput)
      .capability(state::Capability::TimeIndependent)
  );

  // No GPU (e.g. a host only reading schemas): the schema is all that's needed.
  if (gpu::Device::backend() == gpu::Backend::None) return;

  state::registerShaderSPV("compute", COMPUTE_SPV, COMPUTE_SPV_SIZE);
  auto cs = gpu::Device::createShaderModuleByName("compute");
  if (!cs) return;
  s_pso = gpu::Device::createComputePSO(
      cs, "main", gpu::Bindings().tex2d(0).storageTex2d(1).uniform(2));
}

void* create() {
  auto* s = new State();
  s->uniforms = gpu::Device::createBuffer(sizeof(Params), gpu::BufferUsage::Uniform);
  return s;
}

void destroy(void* self) {
  auto* s = static_cast<State*>(self);
  if (!s) return;
  s->uniforms.release();
  delete s;
}

void init(void* self) { (void)self; }

void tick(void* self, double dt) { (void)self; (void)dt; }

void on_state_patched(void* self, int n, const char* pb, const int* off,
                      const int* len, const int* ops) {
  auto* s = static_cast<State*>(self);
  if (!s) return;
  for (int i = 0; i < n; i++) {
    if (ops[i] != state::PatchReplace) continue;
    const char* p = pb + off[i];
    if (state::pathIs(p, len[i], "amount")) {
      s->amount = state::patchFloat(i);
    } else if (state::pathIs(p, len[i], "color")) {
      auto v = state::patchVec3(i);
      s->r = v.x; s->g = v.y; s->b = v.z;
    }
  }
}

void render(void* self, int vp_w, int vp_h) {
  auto* s = static_cast<State*>(self);
  if (!s || vp_w <= 0 || vp_h <= 0 || !s->uniforms.valid()) return;

  auto input = gpu::Device::textureForField("tex_in");
  auto output = gpu::Device::textureForField("tex_out");
  if (!input.valid() || !output.valid()) return;

  Params u = { s->r, s->g, s->b, s->amount };
  s->uniforms.writeOne(u);

  auto cp = gpu::ComputePass::begin();
  cp.setPSO(s_pso);
  cp.setTexture(input, 0, 0);
  cp.setTexture(output, 1, 1);
  cp.setBuffer(s->uniforms, 2);
  cp.dispatch((vp_w + 7) / 8, (vp_h + 7) / 8);
  cp.end();
}

}  // namespace tint
