"""Generate brutal_fold_atlas.h from the brutal-fold research atlas.json.

The atlas is the baked control surface (complexity × order × liveliness) of a
brutalist axonometric-prism field. brutal_fold's CPU `build_params` reads it
directly (it never touches the GPU), so we embed it as a committed C++ header of
flat float arrays — mirroring the prototype's web/src/field.ts + atlas.ts layout:

  term fields    [G,G,B]    row-major (gi*G+gj)*B + ti
  scene scalars  [G,G]      row-major gi*G+gj
  script fields  [G,G,Z,B]  row-major ((gi*G+gj)*Z+z)*B + ti
  b_* = structure 2 (co-folded), b_tilt = its screen shear.

Only the fields the native renderer actually reads are baked: the 8 term fields
and 19 scene scalars (for BOTH structures, so the shader's scene-index offsets
line up), the 4 animation script channels (structure 1 only — structure 2 has no
folded trajectory), and b_tilt. The unused rot/slew script channels are skipped.

Run once and commit the output (no build-time python dependency):

    python3 native/wasm_modules/brutal_fold/gen_atlas.py \
        [--atlas /path/to/brutal-fold/web/public/atlas.json]
"""

import argparse
import json
import os

# Per the prototype atlas.ts: 8 term fields, 19 scene scalars (order MATTERS —
# the shader indexes scene scalars by position), 4 animation script channels.
TERM_FIELDS = ["theta", "mtheta", "shear", "freq", "phase", "h", "amp", "mix"]
SCENE_FIELDS = [
    "sev", "gx", "gy", "form_scale", "thresh", "back_len", "back_ang", "extrude",
    "layers", "sep", "front_detail", "win_dark", "fog", "face", "sky_val", "dc",
    "bold_gain", "rot", "slew",
]
SCRIPT_FIELDS = ["h_amp", "h_om", "h_psi", "phase_drift"]

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_ATLAS = os.path.join(
    HERE, "..", "..", "..", "..", "..", "nano-fx-prototypes", "brutal-fold",
    "web", "public", "atlas.json")


def fmt(v):
    # Compact float literal: drop trailing zeros, keep enough precision. Ensure a
    # decimal point/exponent so the `f` suffix is valid C++ ("1" -> "1.0", not "1f").
    s = f"{float(v):.5g}"
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s


def emit_array(fh, name, values):
    fh.write(f"static const float {name}[{len(values)}] = {{\n")
    line = "  "
    for v in values:
        tok = fmt(v) + "f,"
        if len(line) + len(tok) > 100:
            fh.write(line + "\n")
            line = "  "
        line += tok
    if line.strip():
        fh.write(line + "\n")
    fh.write("};\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--atlas", default=DEFAULT_ATLAS)
    args = ap.parse_args()

    with open(args.atlas) as f:
        atlas = json.load(f)

    G = int(atlas["grid"])
    B = int(atlas["n_terms"])
    Z = int(atlas["n_z"])
    co_fold = int(atlas.get("co_fold", 0))
    h_act = float(atlas.get("constants", {}).get("H_ACT", 0.08))
    tc = [float(v) for v in atlas["tc_centers"]]

    out_path = os.path.join(HERE, "brutal_fold_atlas.h")
    with open(out_path, "w") as fh:
        fh.write("// AUTO-GENERATED by gen_atlas.py from the brutal-fold research atlas. Do not edit.\n")
        fh.write("// Baked control surface: complexity (x) x order (y) x liveliness (z), with a\n")
        fh.write("// co-folded second structure (b_* arrays). CPU-only data — build_params reads it.\n")
        fh.write("#ifndef BRUTAL_FOLD_ATLAS_H\n#define BRUTAL_FOLD_ATLAS_H\n\n")
        fh.write("namespace brutal_fold {\n\n")
        fh.write(f"static const int   BF_GRID   = {G};\n")
        fh.write(f"static const int   BF_NTERMS = {B};\n")
        fh.write(f"static const int   BF_NZ     = {Z};\n")
        fh.write(f"static const int   BF_CO_FOLD = {co_fold};\n")
        fh.write(f"static const float BF_H_ACT  = {fmt(h_act)}f;\n")
        fh.write(f"static const float BF_TC_CENTERS[{Z}] = {{ {', '.join(fmt(v) + 'f' for v in tc)} }};\n\n")

        # Structure 1 + structure 2 (b_) term + scene fields.
        for prefix, cpp_prefix in (("", "BF_"), ("b_", "BF_B_")):
            for name in TERM_FIELDS + SCENE_FIELDS:
                emit_array(fh, cpp_prefix + name.upper(), atlas[prefix + name])
        # Animation script channels — structure 1 only.
        for name in SCRIPT_FIELDS:
            emit_array(fh, "BF_" + name.upper(), atlas[name])
        # Structure 2 screen shear.
        emit_array(fh, "BF_B_TILT", atlas["b_tilt"])

        # Key-moment windows (per cell x z, indexed (gi*G+gj)*Z + z — matches
        # field.nearestCell). Only t1 (center peak) + score + covmax are needed
        # at runtime: score>0 && covmax<=kKmMaxCov marks a usable key moment, and
        # the played span is a FIXED fraction anchored on t1. t0 (onset) is
        # informational and skipped. Absent → key-moment mode has no windows and
        # every cell falls back to the full loop.
        km = atlas.get("keymoments")
        if km:
            fh.write(f"static const int   BF_KM_NFRAMES = {int(km['n_frames'])};\n\n")
            emit_array(fh, "BF_KM_T1", km["t1"])
            emit_array(fh, "BF_KM_SCORE", km["score"])
            emit_array(fh, "BF_KM_COVMAX", km["covmax"])
        else:
            # Degenerate tables so the effect compiles + always falls back to the
            # full loop (score 0 everywhere → no cell has a usable key moment).
            fh.write("static const int   BF_KM_NFRAMES = 0;\n\n")
            for nm in ("BF_KM_T1", "BF_KM_SCORE", "BF_KM_COVMAX"):
                emit_array(fh, nm, [0.0] * (G * G * Z))

        fh.write("} // namespace brutal_fold\n\n")
        fh.write("#endif // BRUTAL_FOLD_ATLAS_H\n")

    print(f"wrote {out_path} ({G}x{G}x{Z}, {B} terms, co_fold={co_fold}, "
          f"H_ACT={h_act}, tc_centers={tc})")


if __name__ == "__main__":
    main()
