// test_comp_time.cpp — replays the shared comp goldens against the C++ ports
// (warp_curve.h, clip_time.h, comp_transport.h, precise_gate.h).
//
// The fixtures in tests/fixtures/comp/ are GENERATED by the TS reference
// implementation (web/.../engine/comp-goldens.test.ts, UPDATE_GOLDENS=1) and
// verified by both suites — that pair is the lock-step contract for the
// composition executor's timing/gate logic.
//
// Tolerances: all the math is IEEE-identical across JS/C++ except sin (warp
// waves, smooth noise), which may differ by ~1 ulp; localSecondsPerBeat's
// central difference amplifies that. 1e-7 absolute is comfortably above the
// worst-case wobble and far below any real algorithmic divergence. Expected
// FRAMES are exact — the generator only emits them away from floor boundaries.

#include "sketch/comp/clip_time.h"
#include "sketch/comp/comp_model.h"
#include "sketch/comp/comp_transport.h"
#include "sketch/comp/precise_gate.h"
#include "sketch/comp/warp_curve.h"

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include <fstream>
#include <set>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

using Catch::Matchers::WithinAbs;
using json = nlohmann::json;

namespace {

constexpr double kTol = 1e-7;

json loadFixture(const std::string& name) {
  const std::string path = std::string(COMP_FIXTURES_DIR) + "/" + name;
  std::ifstream f(path);
  REQUIRE(f.good());  // missing ⇒ run UPDATE_GOLDENS=1 npx vitest run comp-goldens (web/)
  json j = json::parse(f, nullptr, false);
  REQUIRE(!j.is_discarded());
  return j;
}

std::vector<comp::WarpSegment> segmentsOf(const json& arr) {
  std::vector<comp::WarpSegment> segs;
  for (const auto& s : arr) segs.push_back(comp::WarpSegment::fromJson(s));
  return segs;
}

comp::WarpClock clockOf(const json& spec) {
  return comp::WarpClock(
      comp::WarpCurve(segmentsOf(spec["segments"]), spec["totalBeats"].get<double>()),
      spec["bpm"].get<double>());
}

}  // namespace

TEST_CASE("warp goldens — WarpCurve/WarpClock match the TS reference", "[comp]") {
  const json fx = loadFixture("warp.json");
  for (const auto& c : fx["cases"]) {
    INFO("case " << c["name"].get<std::string>());
    const auto clock = clockOf(c);
    for (const auto& s : c["samples"]) {
      const double beat = s["beat"].get<double>();
      CHECK_THAT(clock.curve().unitsAt(beat), WithinAbs(s["units"].get<double>(), kTol));
      CHECK_THAT(clock.secondsAt(beat), WithinAbs(s["seconds"].get<double>(), kTol));
    }
    for (const auto& s : c["inverse"]) {
      CHECK_THAT(clock.curve().beatAt(s["units"].get<double>()),
                 WithinAbs(s["beat"].get<double>(), kTol));
    }
    for (const auto& s : c["invSeconds"]) {
      CHECK_THAT(clock.beatAtSeconds(s["seconds"].get<double>()),
                 WithinAbs(s["beat"].get<double>(), kTol));
    }
    for (const auto& s : c["local"]) {
      CHECK_THAT(clock.localSecondsPerBeat(s["beat"].get<double>()),
                 WithinAbs(s["spb"].get<double>(), kTol));
    }
    CHECK_THAT(clock.durationSeconds(), WithinAbs(c["durationSeconds"].get<double>(), kTol));
  }
}

TEST_CASE("clip-time goldens — clipSourceTimeAt/FrameAt match the TS reference", "[comp]") {
  const json fx = loadFixture("clip-time.json");
  for (const auto& c : fx["cases"]) {
    INFO("case " << c["name"].get<std::string>());
    const auto loop = comp::ClipLoopConfig::fromJson(c["loop"]);
    const auto clock = clockOf(c["clock"]);
    comp::ClipTimeCtx ctx;
    ctx.startBeat = c["ctx"]["startBeat"].get<double>();
    ctx.lengthBeat = c["ctx"]["lengthBeat"].get<double>();
    ctx.videoDurSec = c["ctx"]["videoDurSec"].get<double>();
    ctx.seed = c["ctx"].value("seed", 0.0);
    ctx.clock = &clock;
    const double fps = c["fps"].get<double>();
    const int32_t frameCount = c["frameCount"].get<int32_t>();

    for (const auto& s : c["samples"]) {
      const double beat = s["beat"].get<double>();
      INFO("beat " << beat);
      const auto vt = comp::clipSourceTimeAt(loop, ctx, beat);
      if (s["timeSec"].is_null()) {
        CHECK(!vt.has_value());
      } else {
        REQUIRE(vt.has_value());
        CHECK_THAT(*vt, WithinAbs(s["timeSec"].get<double>(), kTol));
      }
      if (s.contains("frame")) {
        const auto frame = comp::clipSourceFrameAt(loop, ctx, beat, fps, frameCount);
        if (s["frame"].is_null()) {
          CHECK(!frame.has_value());
        } else {
          REQUIRE(frame.has_value());
          CHECK(*frame == s["frame"].get<int32_t>());
        }
      }
    }
  }

  for (const auto& s : fx["noiseSeeds"]) {
    CHECK_THAT(comp::clipNoiseSeed(s["id"].get<std::string>()),
               WithinAbs(s["seed"].get<double>(), 0.0));  // integer hash → exact
  }
}

TEST_CASE("transport goldens — TransportController matches the TS reference", "[comp]") {
  const json fx = loadFixture("transport.json");
  for (const auto& c : fx["cases"]) {
    INFO("case " << c["name"].get<std::string>());
    const auto clock = clockOf(c["clock"]);
    comp::TransportController tc;
    comp::TransportState s;
    s.playing = c["state"]["playing"].get<bool>();
    s.positionBeat = c["state"]["positionBeat"].get<double>();
    s.loopEnabled = c["state"]["loopEnabled"].get<bool>();
    s.loopStartBeat = c["state"]["loopStartBeat"].get<double>();
    s.loopEndBeat = c["state"]["loopEndBeat"].get<double>();

    const auto& steps = c["steps"];
    const auto& expected = c["expect"];
    REQUIRE(steps.size() == expected.size());
    for (size_t i = 0; i < steps.size(); i++) {
      const auto& step = steps[i];
      INFO("step " << i);
      if (step.contains("playing")) s.playing = step["playing"].get<bool>();
      if (step.contains("scrubBeat")) s.positionBeat = step["scrubBeat"].get<double>();
      tc.advance(s, clock, step["dt"].get<double>());
      CHECK_THAT(s.positionBeat, WithinAbs(expected[i]["beat"].get<double>(), kTol));
      CHECK_THAT(tc.secondsAt(s, clock), WithinAbs(expected[i]["seconds"].get<double>(), kTol));
    }
  }
}

TEST_CASE("gate goldens — precise-gate decisions match the TS reference", "[comp]") {
  const json fx = loadFixture("gate.json");

  for (const auto& c : fx["shouldHold"]) {
    CHECK(comp::shouldHoldPrecise(c["precise"].get<bool>(), c["force"].get<bool>(),
                                  c["activeVideoCount"].get<int>(), c["ready"].get<bool>()) ==
          c["expect"].get<bool>());
  }

  for (const auto& c : fx["videoInputsReady"]) {
    std::vector<std::string> active;
    for (const auto& id : c["active"]) active.push_back(id.get<std::string>());
    std::set<std::string> ready;
    for (const auto& id : c["readyIds"]) ready.insert(id.get<std::string>());
    CHECK(comp::videoInputsReady(active, c["hasPump"].get<bool>(),
                                 [&](const std::string& id) { return ready.count(id) > 0; }) ==
          c["expect"].get<bool>());
  }

  struct Item {
    std::string clipId;
    std::string tag;
    bool operator==(const Item& o) const { return clipId == o.clipId && tag == o.tag; }
  };
  auto itemsOf = [](const json& arr) {
    std::vector<Item> out;
    for (const auto& e : arr) out.push_back({e["clipId"].get<std::string>(), e["tag"].get<std::string>()});
    return out;
  };
  for (const auto& c : fx["pumpActiveSet"]) {
    const auto got = comp::pumpActiveSet(c["holding"].get<bool>(), itemsOf(c["target"]),
                                         itemsOf(c["displayed"]),
                                         [](const Item& i) { return i.clipId; });
    const auto want = itemsOf(c["expect"]);
    REQUIRE(got.size() == want.size());
    for (size_t i = 0; i < got.size(); i++) {
      INFO("index " << i);
      CHECK(got[i] == want[i]);
    }
  }
}
