// test_comp_build.cpp — replays the build.json goldens against the C++
// composition-executor ports: document parse (comp_model.h), effect catalog
// (comp_catalog.h), tree eval + automation (comp_eval.h), and the composite
// sketch build (sketch_build.h).
//
// The fixture is generated by the TS reference (web comp-goldens.test.ts,
// UPDATE_GOLDENS=1). For every (composition, beat) it snapshots the FULL built
// sketch JSON + the automation entries; this suite must reproduce them
// deep-equal. Deep-equal with a numeric tolerance: automation/rail-base values
// evaluate through the native float envelope.h (TS twin runs in double), and
// startSec goes through sin (~1 ulp) — everything else matches bit-exactly.

#include "sketch/comp/comp_catalog.h"
#include "sketch/comp/comp_eval.h"
#include "sketch/comp/comp_model.h"
#include "sketch/comp/sketch_build.h"
#include "sketch/comp/warp_curve.h"

#include <catch2/catch_test_macros.hpp>

#include <cmath>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

using json = nlohmann::json;

namespace {

json loadFixture(const std::string& name) {
  const std::string path = std::string(COMP_FIXTURES_DIR) + "/" + name;
  std::ifstream f(path);
  REQUIRE(f.good());  // missing ⇒ run UPDATE_GOLDENS=1 npx vitest run comp-goldens (web/)
  json j = json::parse(f, nullptr, false);
  REQUIRE(!j.is_discarded());
  return j;
}

bool numbersClose(double a, double b) {
  const double diff = std::abs(a - b);
  return diff <= 1e-9 || diff <= 1e-6 * std::max(std::abs(a), std::abs(b));
}

/** Deep JSON equality with numeric tolerance; records the first divergence path. */
bool deepClose(const json& a, const json& b, std::string path, std::string& firstDiff) {
  if (a.is_number() && b.is_number()) {
    if (numbersClose(a.get<double>(), b.get<double>())) return true;
    firstDiff = path + ": " + a.dump() + " vs " + b.dump();
    return false;
  }
  if (a.type() != b.type()) {
    // null vs anything, object vs array, string vs number, bool mismatch...
    if (a == b) return true;
    firstDiff = path + ": type " + std::string(a.type_name()) + " vs " + b.type_name() +
                " (" + a.dump() + " vs " + b.dump() + ")";
    return false;
  }
  if (a.is_object()) {
    for (auto& [k, v] : a.items()) {
      if (!b.contains(k)) {
        firstDiff = path + "." + k + ": missing in expected";
        return false;
      }
      if (!deepClose(v, b[k], path + "." + k, firstDiff)) return false;
    }
    for (auto& [k, v] : b.items()) {
      if (!a.contains(k)) {
        firstDiff = path + "." + k + ": missing in actual";
        return false;
      }
    }
    return true;
  }
  if (a.is_array()) {
    if (a.size() != b.size()) {
      firstDiff = path + ": array size " + std::to_string(a.size()) + " vs " +
                  std::to_string(b.size());
      return false;
    }
    for (size_t i = 0; i < a.size(); i++) {
      if (!deepClose(a[i], b[i], path + "[" + std::to_string(i) + "]", firstDiff)) return false;
    }
    return true;
  }
  if (a == b) return true;
  firstDiff = path + ": " + a.dump() + " vs " + b.dump();
  return false;
}

void checkDeepClose(const json& actual, const json& expected, const std::string& what) {
  std::string firstDiff;
  const bool ok = deepClose(actual, expected, what, firstDiff);
  INFO(firstDiff);
  CHECK(ok);
}

/** Register the shared plugin catalog (schemas + capabilities) from build.json. */
comp::Catalog catalogFrom(const json& fx) {
  comp::Catalog cat;
  for (const auto& p : fx["plugins"]) {
    cat.registerSchema(p["id"].get<std::string>(), p["schema"]);
    cat.registerCapabilities(p["id"].get<std::string>(), p["capabilities"]);
  }
  return cat;
}

/** Replay one fixture's `cases` array against the C++ build. */
void replayCases(const json& cases, const comp::Catalog& cat) {
  for (const auto& c : cases) {
    const std::string name = c["name"].get<std::string>();
    INFO("case " << name);
    const comp::CompositionM comp = comp::parseComposition(c["composition"]);
    const bool ignoreSolo = c.value("ignoreSolo", false);
    const bool clipLoopMode = c.value("clipAutoTiming", std::string("loop")) == "loop";

    // The live path's cached clock: makeWarpClock(composition).
    const comp::WarpClock clock(
        comp::WarpCurve(comp::derivedWarpSegments(comp), comp::compositionLengthBeats(comp)),
        comp.baseBPM);

    for (const auto& frame : c["frames"]) {
      const double beat = frame["beat"].get<double>();
      INFO("beat " << beat);

      const auto build = comp::buildCompositeRenderAtBeat(comp, cat, clock, beat, ignoreSolo);
      if (frame["sketch"].is_null()) {
        CHECK(!build.hasContent);
      } else {
        REQUIRE(build.hasContent);
        checkDeepClose(build.sketch, frame["sketch"], "sketch");
      }

      const json automation = comp::automationEntriesAtBeat(comp, beat, ignoreSolo, clipLoopMode);
      checkDeepClose(automation, frame["automation"], "automation");
    }
  }
}

}  // namespace

TEST_CASE("build goldens — tree eval + sketch build + automation match TS", "[comp]") {
  const json fx = loadFixture("build.json");
  replayCases(fx["cases"], catalogFrom(fx));
}

// The sequence cases live in their OWN fixture: build.json is frozen and its
// key order is the TS reference's insertion order, which nlohmann's writer does
// not preserve — regenerating in place would rewrite all 12 existing cases for
// no reason. Same plugin catalog, same replay.
TEST_CASE("build goldens — sequence clips", "[comp][comp_sequence]") {
  const json seq = loadFixture("build-sequence.json");
  replayCases(seq["cases"], catalogFrom(loadFixture("build.json")));
}

// ─────────────────────────────────────────────────────────────────────────────
// SEQUENCE-CLIP golden generator.
//
// The original TS reference (clip-sketch.ts / composite-frame.ts) was deleted
// when the offline exporter moved onto the comp executor, so there is no
// cross-host oracle left to generate a composite golden from. These cases are
// therefore CHANGE DETECTORS, not cross-validation — they pin the exact node
// structure, instance keys and wire numbering that compositeSequence emits
// today, so a refactor that silently renumbers wires or reorders the interior
// (the class the foldClipModulation extraction risked) fails loudly instead of
// quietly changing every user's render.
//
// Regenerate deliberately, and READ THE DIFF before committing:
//     ./build/test_comp_build "[.gen]"
// Hidden by the leading dot — the normal run replays them like any other case.
// ─────────────────────────────────────────────────────────────────────────────

namespace {

json gDevice(const std::string& id, const std::string& type, json state = json::object()) {
  json d = {{"id", id}, {"moduleType", type}, {"name", type}, {"capabilities", json::array()}};
  if (!state.empty()) d["state"] = std::move(state);
  return d;
}

json gClip(const std::string& id, double startBeat, double lengthBeat, json devices,
           json over = json::object()) {
  json c = {{"id", id}, {"name", id}, {"startBeat", startBeat}, {"lengthBeat", lengthBeat},
            {"kind", "effect"}, {"sketch", {{"devices", std::move(devices)}}},
            {"loop", {{"mode", "time"}, {"startSec", 0}, {"speed", 1},
                      {"direction", "forward"}}},
            {"automation", json::array()}, {"exports", json::array()},
            {"warps", json::array()}};
  c.update(over);
  return c;
}

json gTrack(const std::string& id, json clips, json over = json::object()) {
  json t = {{"id", id}, {"name", id}, {"kind", "track"}, {"parentId", nullptr},
            {"sketch", {{"devices", json::array()}}}, {"automation", json::array()},
            {"clips", std::move(clips)}};
  t.update(over);
  return t;
}

json gComposition(json tracks) {
  return {{"meta", {{"resolution", {{"width", 1920}, {"height", 1080}}},
                    {"baseBPM", 120}, {"timeSignature", json::array({4, 4})}}},
          {"tracks", std::move(tracks)}, {"rails", json::array()}};
}

/** A sequence clip: `laneDevices` is the interior lane's FX bus, `ownDevices`
 *  the sequence clip's own chain (which runs OVER the interior composite). */
json gSequenceClip(const std::string& id, double startBeat, double lengthBeat,
                   const std::string& laneId, json subClips, json ownDevices,
                   json laneDevices = json::array(), json ownWires = json::array()) {
  json lane = {{"id", laneId}, {"name", laneId}, {"kind", "track"}, {"parentId", nullptr},
               {"sketch", {{"devices", std::move(laneDevices)}}},
               {"automation", json::array()}, {"clips", std::move(subClips)}};
  json over = {{"kind", "sequence"}, {"sequence", std::move(lane)}};
  json c = gClip(id, startBeat, lengthBeat, std::move(ownDevices), over);
  if (!ownWires.empty()) c["sketch"]["wires"] = std::move(ownWires);
  return c;
}

/** Snapshot (sketch, automation) at each beat — the frame shape build.json uses. */
json gFrames(const comp::CompositionM& comp, const comp::Catalog& cat,
             const std::vector<double>& beats) {
  const comp::WarpClock clock(
      comp::WarpCurve(comp::derivedWarpSegments(comp), comp::compositionLengthBeats(comp)),
      comp.baseBPM);
  json frames = json::array();
  for (const double beat : beats) {
    const auto build = comp::buildCompositeRenderAtBeat(comp, cat, clock, beat, false);
    frames.push_back({{"beat", beat},
                      {"sketch", build.hasContent ? build.sketch : json()},
                      {"automation", comp::automationEntriesAtBeat(comp, beat, false, true)}});
  }
  return frames;
}

}  // namespace

TEST_CASE("[.gen] regenerate build-sequence.json", "[.gen]") {
  const std::string path = std::string(COMP_FIXTURES_DIR) + "/build-sequence.json";
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));

  json cases = json::array();

  // sequence-basic — the whole four-level stack in one case: interior sub-clip
  // → interior lane FX bus → the sequence clip's OWN chain → the parent track's
  // blend, over a second track so the blend-up has something to land on. Beats
  // 1 and 5 straddle the interior switch; beat 9 is past the sequence entirely
  // (the parent track must fall back to contributing nothing).
  {
    json comp = gComposition(json::array({
        gTrack("t1", json::array({gSequenceClip(
                   "seq", 0, 8, "lane1",
                   json::array({gClip("sub1", 0, 4,
                                      json::array({gDevice("sc", "source.solid_color")})),
                                gClip("sub2", 4, 4,
                                      json::array({gDevice("nz", "source.noise")}))}),
                   json::array({gDevice("sat", "color.saturate")}),
                   json::array({gDevice("linv", "color.invert")}))}),
               {{"level", 0.8}}),
        gTrack("t2", json::array({gClip("base", 0, 16,
                                        json::array({gDevice("bn", "source.noise")}))})),
    }));
    cases.push_back({{"name", "sequence-basic"},
                     {"composition", comp},
                     {"frames", gFrames(comp::parseComposition(comp), cat, {1, 5, 9})}});
  }

  // sequence-underlying-seed — the interior seeds from `underlying`, NOT from a
  // transparent input: an interior holding ONLY an effect must process the
  // track below it. Also pins clip-modulation wire numbering on both levels at
  // once (an LFO inside the sub-clip AND one on the sequence clip's own chain),
  // which is what keeps compositeSequence and compositeClip from drifting.
  {
    json subWires = json::array({{{"id", "w1"},
                                  {"src", {{"instanceKey", "slfo"}, {"field", "output"}}},
                                  {"dest", {{"instanceKey", "ssat"}, {"field", "prescale"}}},
                                  {"combine", "add"},
                                  {"magnitude", "signed"}}});
    json ownWires = json::array({{{"id", "w2"},
                                  {"src", {{"instanceKey", "olfo"}, {"field", "output"}}},
                                  {"dest", {{"instanceKey", "osat"}, {"field", "prescale"}}},
                                  {"combine", "add"},
                                  {"magnitude", "signed"}}});
    json sub = gClip("fxonly", 0, 8,
                     json::array({gDevice("ssat", "color.saturate"),
                                  gDevice("slfo", "mod.source.lfo",
                                          {{"rate", 0.25}})}));
    sub["sketch"]["wires"] = subWires;
    json comp = gComposition(json::array({
        gTrack("t1", json::array({gSequenceClip(
                   "seq", 0, 8, "lane1", json::array({sub}),
                   json::array({gDevice("osat", "color.saturate"),
                                gDevice("olfo", "mod.source.lfo", {{"rate", 0.5}})}),
                   json::array(), ownWires)})),
        gTrack("t2", json::array({gClip("under", 0, 16,
                                        json::array({gDevice("un", "source.noise")}))})),
    }));
    cases.push_back({{"name", "sequence-underlying-seed"},
                     {"composition", comp},
                     {"frames", gFrames(comp::parseComposition(comp), cat, {2})}});
  }

  std::ofstream out(path);
  REQUIRE(out.good());
  out << json{{"cases", std::move(cases)}}.dump(1) << "\n";
  WARN("regenerated " << path << " — READ THE DIFF");
}

// ─────────────────────────────────────────────────────────────────────────────
// MULTIPLE SOURCES IN ONE CLIP.
//
// The build used to keep only the FIRST generator in a clip's chain and drop
// every later one, so a second source (two source.text.plain with different
// copy, say) simply never rendered. The first generator still ANCHORS the layer;
// the rest follow it in declaration order, so a source that reads tex_in
// composites over what came before and one that ignores it wins outright.
namespace {

/** A one-track composition whose single clip carries `devices` in order. */
json compWithDevices(const std::vector<std::pair<std::string, std::string>>& devices) {
  json devs = json::array();
  for (const auto& [id, type] : devices) {
    devs.push_back({{"id", id}, {"moduleType", type}, {"name", type},
                    {"capabilities", json::array()}, {"state", json::object()}});
  }
  return {
    {"meta", {{"resolution", {{"width", 64}, {"height", 64}}},
              {"baseBPM", 120}, {"timeSignature", {4, 4}}}},
    {"tracks", json::array({
      {{"id", "t1"}, {"name", "t1"}, {"kind", "track"}, {"parentId", nullptr},
       {"sketch", {{"devices", json::array()}}}, {"automation", json::array()},
       {"clips", json::array({
         {{"id", "c1"}, {"name", "c1"}, {"startBeat", 0}, {"lengthBeat", 8},
          {"kind", "effect"}, {"sketch", {{"devices", devs}}},
          {"automation", json::array()}, {"exports", json::array()},
          {"warps", json::array()}, {"blendMode", 0}}})}},
    })},
    {"rails", json::array()},
  };
}

/** Ordered `instance_key`s of the built chain. */
std::vector<std::string> chainKeys(const comp::SketchBuild& b) {
  std::vector<std::string> out;
  for (const auto& e : b.sketch["chain"]) out.push_back(e.value("instance_key", std::string()));
  return out;
}

comp::SketchBuild buildOne(const json& compJson, const comp::Catalog& cat) {
  const comp::CompositionM c = comp::parseComposition(compJson);
  const comp::WarpClock clock(
      comp::WarpCurve(comp::derivedWarpSegments(c), comp::compositionLengthBeats(c)), c.baseBPM);
  return comp::buildCompositeRenderAtBeat(c, cat, clock, 0.0, false);
}

}  // namespace

TEST_CASE("a clip's SECOND generator stays in the chain", "[comp]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  REQUIRE(cat.isGenerator("source.solid_color"));
  REQUIRE(cat.isGenerator("source.noise"));

  SECTION("two sources render in declaration order, the first anchoring the layer") {
    const auto b = buildOne(compWithDevices({{"g1", "source.solid_color"},
                                             {"g2", "source.noise"}}), cat);
    REQUIRE(b.hasContent);
    const auto keys = chainKeys(b);
    // arr_bg is the opaque backdrop under all clips, clip_c1_blend composites the
    // layer over it; between them the clip's own devices, in order.
    CHECK(keys == std::vector<std::string>{
        "arr_bg", "clip_c1_g1", "clip_c1_g2", "clip_c1_blend"});
  }

  SECTION("effects between two sources keep their order relative to each other") {
    const auto b = buildOne(compWithDevices({{"g1", "source.solid_color"},
                                             {"fx", "color.invert"},
                                             {"g2", "source.noise"}}), cat);
    REQUIRE(b.hasContent);
    const auto keys = chainKeys(b);
    CHECK(keys == std::vector<std::string>{
        "arr_bg", "clip_c1_g1", "clip_c1_fx", "clip_c1_g2", "clip_c1_blend"});
  }

  SECTION("a generator that is not first is still hoisted to anchor the layer") {
    // [fx, gen] must not start the chain on an effect — there would be nothing
    // to process. The generator leads; the effect follows it (the pre-existing
    // rule, unchanged).
    const auto b = buildOne(compWithDevices({{"fx", "color.invert"},
                                             {"g1", "source.noise"}}), cat);
    REQUIRE(b.hasContent);
    const auto keys = chainKeys(b);
    CHECK(keys == std::vector<std::string>{
        "arr_bg", "clip_c1_g1", "clip_c1_fx", "clip_c1_blend"});
  }
}

TEST_CASE("comp-built sketches carry no sidecar-canvas keys", "[comp]") {
  // The arrangement builds purely LINEAR chains, and its output is a
  // byte-for-byte golden shared with web/src/views/arrangement/engine/. The
  // sidecar canvas adds two optional keys to the sketch schema (ModuleEntry
  // `canvas` and Sketch `execOrder`); neither may ever appear here, or the
  // goldens drift and comp clips silently gain canvas semantics.
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  const auto b = buildOne(compWithDevices({{"g1", "source.solid_color"},
                                           {"fx", "color.invert"}}), cat);
  REQUIRE(b.hasContent);
  CHECK_FALSE(b.sketch.contains("execOrder"));
  for (const auto& e : b.sketch["chain"]) {
    INFO("entry " << e.value("instance_key", std::string()));
    CHECK_FALSE(e.contains("canvas"));
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// CLIPLESS layers: a timeline track with no clips runs its own sketch as its
// content — generators included — continuously.
// ─────────────────────────────────────────────────────────────────────────────

namespace {

json deviceJson(const std::string& id, const std::string& type, json state = json::object()) {
  return {{"id", id}, {"moduleType", type}, {"name", type},
          {"capabilities", json::array()}, {"state", std::move(state)}};
}

/** A timeline track. `clipDevices` empty ⇒ no clips at all (clipless). */
json trackJson(const std::string& id, json sketchDevices, json clipDevices = json::array(),
               json extra = json::object()) {
  json clips = json::array();
  if (!clipDevices.empty()) {
    clips.push_back({{"id", id + "_c"}, {"name", id + "_c"}, {"startBeat", 0},
                     {"lengthBeat", 8}, {"kind", "effect"},
                     {"sketch", {{"devices", std::move(clipDevices)}}},
                     {"automation", json::array()}, {"exports", json::array()},
                     {"warps", json::array()}, {"blendMode", 0}});
  }
  json t = {{"id", id}, {"name", id}, {"kind", "track"}, {"parentId", nullptr},
            {"sketch", {{"devices", std::move(sketchDevices)}}},
            {"automation", json::array()}, {"clips", std::move(clips)}};
  for (auto& [k, v] : extra.items()) t[k] = v;
  return t;
}

json compOf(json tracks) {
  return {{"meta", {{"resolution", {{"width", 64}, {"height", 64}}},
                    {"baseBPM", 120}, {"timeSignature", {4, 4}}}},
          {"tracks", std::move(tracks)},
          {"rails", json::array()}};
}

}  // namespace

TEST_CASE("clipless layer: a sketch with a generator is a source layer", "[comp][clipless]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  // The generator is hoisted to anchor the chain, exactly as in a clip.
  const auto b = buildOne(compOf(json::array({
      trackJson("t1", json::array({deviceJson("fx", "color.invert"),
                                   deviceJson("g", "source.noise")})),
  })), cat);
  REQUIRE(b.hasContent);
  CHECK(chainKeys(b) == std::vector<std::string>{
      "arr_bg", "track_t1_g", "track_t1_fx", "track_t1_blend"});
  // The layer's opacity rides its blend node.
  CHECK(b.layerTargets["t1"]["instanceKey"] == "track_t1_blend");
  CHECK(b.layerTargets["t1"]["field"] == "opacity");
}

TEST_CASE("clipless layer: an effect-only sketch processes the stack", "[comp][clipless]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  const auto b = buildOne(compOf(json::array({
      trackJson("src", json::array(), json::array({deviceJson("g", "source.solid_color")})),
      trackJson("adj", json::array({deviceJson("fx", "color.invert")}), json::array(),
                {{"level", 0.5}}),
  })), cat);
  REQUIRE(b.hasContent);
  CHECK(chainKeys(b) == std::vector<std::string>{
      "arr_bg", "clip_src_c_g", "clip_src_c_blend", "track_adj_fx"});
  // An adjustment layer carries its level as the reserved wet/dry key.
  CHECK(b.sketch["instances"]["track_adj_fx"]["state"]["__opacity__"] == 0.5);
  CHECK(b.layerTargets["adj"]["field"] == "__opacity__");
}

TEST_CASE("clipless layer: only tracks with NO clips qualify", "[comp][clipless]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  SECTION("a track whose clips are all elsewhere in time keeps its FX-bus role") {
    json t = trackJson("t1", json::array({deviceJson("g", "source.noise")}),
                       json::array({deviceJson("cg", "source.solid_color")}));
    t["clips"][0]["startBeat"] = 100;  // not active at beat 0
    const auto b = buildOne(compOf(json::array({t})), cat);
    CHECK_FALSE(b.hasContent);
  }
  SECTION("an empty sketch is no layer") {
    const auto b = buildOne(compOf(json::array({trackJson("t1", json::array())})), cat);
    CHECK_FALSE(b.hasContent);
  }
  SECTION("unknown modules only is no layer (the backdrop alone)") {
    const auto b = buildOne(compOf(json::array({
        trackJson("t1", json::array({deviceJson("x", "nope.unknown")}))})), cat);
    REQUIRE(b.hasContent);
    CHECK(chainKeys(b) == std::vector<std::string>{"arr_bg"});
  }
}

TEST_CASE("clipless layer: its wires and automation resolve to track keys", "[comp][clipless]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  json t = trackJson("t1", json::array({deviceJson("g", "source.solid_color"),
                                         deviceJson("lfo", "mod.source.lfo"),
                                         deviceJson("fx", "color.saturate")}));
  t["sketch"]["wires"] = json::array({
      {{"id", "w1"}, {"src", {{"instanceKey", "lfo"}, {"field", "output"}}},
       {"dest", {{"instanceKey", "fx"}, {"field", "amount"}}}, {"combine", "add"}}});
  t["automation"] = json::array({
      {{"id", "l1"}, {"targetDeviceId", "fx"}, {"targetField", "amount"}, {"label", "amt"},
       {"points", json::array({{{"x", 0}, {"y", 0.25}}, {{"x", 8}, {"y", 0.25}}})}}});
  const json c = compOf(json::array({t}));
  const auto b = buildOne(c, cat);
  REQUIRE(b.hasContent);
  bool found = false;
  for (const auto& w : b.sketch["wires"]) {
    if (w["src"]["instanceKey"] == "track_t1_lfo" && w["dest"]["instanceKey"] == "track_t1_fx") {
      found = true;
      CHECK(w["dest"]["field"] == "amount");
    }
  }
  CHECK(found);
  const json autos = comp::automationEntriesAtBeat(comp::parseComposition(c), 0.0);
  bool laneFound = false;
  for (const auto& e : autos) {
    if (e["instance"] == "track_t1_fx" && e["field"] == "amount") laneFound = true;
  }
  CHECK(laneFound);
}

// ─────────────────────────────────────────────────────────────────────────────
// Composition I/O: routes between track ports and texture fields.
// ─────────────────────────────────────────────────────────────────────────────

namespace {

json portEnd(const std::string& track, const std::string& port) {
  return {{"kind", "port"}, {"trackId", track}, {"portId", port}};
}
json fieldEnd(const std::string& track, const std::string& clip, const std::string& dev,
              const std::string& field) {
  json e = {{"kind", "field"}, {"trackId", track}, {"deviceId", dev}, {"field", field}};
  if (!clip.empty()) e["clipId"] = clip;
  return e;
}
json route(const std::string& id, json src, json dest) {
  return {{"id", id}, {"src", std::move(src)}, {"dest", std::move(dest)}};
}

/** One wire in the build from `srcKey` to `destKey`, or null. */
json findWire(const comp::SketchBuild& b, const std::string& srcKey, const std::string& destKey,
              const std::string& destField = "") {
  for (const auto& w : b.sketch["wires"]) {
    if (w["src"]["instanceKey"] == srcKey && w["dest"]["instanceKey"] == destKey &&
        (destField.empty() || w["dest"]["field"] == destField))
      return w;
  }
  return nullptr;
}

comp::SketchBuild buildAt(const json& compJson, const comp::Catalog& cat, double beat) {
  const comp::CompositionM c = comp::parseComposition(compJson);
  const comp::WarpClock clock(
      comp::WarpCurve(comp::derivedWarpSegments(c), comp::compositionLengthBeats(c)), c.baseBPM);
  return comp::buildCompositeRenderAtBeat(c, cat, clock, beat, false);
}

size_t indexOf(const std::vector<std::string>& keys, const std::string& k) {
  for (size_t i = 0; i < keys.size(); i++) if (keys[i] == k) return i;
  return keys.size();
}

}  // namespace

TEST_CASE("io: a send carries a track's output into a field on another track", "[comp][io]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  json c = compOf(json::array({
      trackJson("a", json::array(), json::array({deviceJson("g", "source.solid_color")})),
      trackJson("b", json::array({deviceJson("inv", "color.invert")})),
  }));
  c["routes"] = json::array({route("r1", portEnd("a", "__out__"),
                                   fieldEnd("b", "", "inv", "mask"))});
  const auto b = buildOne(c, cat);
  REQUIRE(b.hasContent);
  const json w = findWire(b, "clip_a_c_g", "track_b_inv", "mask");
  REQUIRE(w.is_object());
  CHECK(w["src"]["field"] == "tex_out");
  CHECK(b.routeStatus["r1"]["live"] == true);
  CHECK(b.routeStatus["r1"]["delayed"] == false);
}

TEST_CASE("io: a source rendering after its reader is marked delayed", "[comp][io]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  json c = compOf(json::array({
      trackJson("a", json::array(), json::array({deviceJson("g", "source.solid_color"),
                                                 deviceJson("fx", "color.invert")})),
      trackJson("b", json::array(), json::array({deviceJson("n", "source.noise")})),
  }));
  c["routes"] = json::array({route("r1", portEnd("b", "__out__"),
                                   fieldEnd("a", "a_c", "fx", "mask"))});
  const auto b = buildOne(c, cat);
  REQUIRE(findWire(b, "clip_b_c_n", "clip_a_c_fx", "mask").is_object());
  CHECK(b.routeStatus["r1"]["delayed"] == true);
}

TEST_CASE("io: a named out port is fed from inside the track and survives a clip change",
          "[comp][io]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  json a = trackJson("a", json::array(), json::array({deviceJson("g", "source.solid_color")}));
  a["clips"].push_back({{"id", "a_c2"}, {"name", "a_c2"}, {"startBeat", 8}, {"lengthBeat", 8},
                        {"kind", "effect"},
                        {"sketch", {{"devices", json::array({deviceJson("g2", "source.noise")})}}},
                        {"automation", json::array()}, {"exports", json::array()},
                        {"warps", json::array()}, {"blendMode", 0}});
  a["ports"] = json::array({{{"id", "L"}, {"name", "Left"}, {"dir", "out"}}});
  json c = compOf(json::array({a, trackJson("b", json::array({deviceJson("inv", "color.invert")}))}));
  c["routes"] = json::array({
      route("f1", fieldEnd("a", "a_c", "g", "left_out"), portEnd("a", "L")),
      route("f2", fieldEnd("a", "a_c2", "g2", "left_out"), portEnd("a", "L")),
      route("s1", portEnd("a", "L"), fieldEnd("b", "", "inv", "mask")),
  });
  const auto b0 = buildAt(c, cat, 1.0);
  const json w0 = findWire(b0, "clip_a_c_g", "track_b_inv", "mask");
  REQUIRE(w0.is_object());
  CHECK(w0["src"]["field"] == "left_out");
  CHECK(b0.routeStatus["f1"]["live"] == true);
  CHECK(b0.routeStatus["f2"]["live"] == false);  // that clip isn't playing
  const auto b1 = buildAt(c, cat, 9.0);
  CHECK(findWire(b1, "clip_a_c2_g2", "track_b_inv", "mask").is_object());
  CHECK(b1.routeStatus["s1"]["live"] == true);
}

TEST_CASE("io: a routed __in__ makes an effect-only track a source layer", "[comp][io]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  SECTION("clipless") {
    json c = compOf(json::array({
        trackJson("a", json::array(), json::array({deviceJson("g", "source.solid_color")})),
        trackJson("b", json::array({deviceJson("inv", "color.invert")})),
    }));
    c["routes"] = json::array({route("r1", portEnd("a", "__out__"), portEnd("b", "__in__"))});
    const auto b = buildOne(c, cat);
    const auto keys = chainKeys(b);
    // The relay heads b's chain, and b blends over the stack like a source.
    CHECK(indexOf(keys, "track_b_in") < indexOf(keys, "track_b_inv"));
    CHECK(indexOf(keys, "track_b_blend") < keys.size());
    CHECK(findWire(b, "clip_a_c_g", "track_b_in", "1").is_object());
    CHECK(findWire(b, "clip_a_c_g", "track_b_in", "0").is_object());
    CHECK(findWire(b, "track_b_inv", "track_b_blend", "1").is_object());
  }
  SECTION("an effect-only clip") {
    json c = compOf(json::array({
        trackJson("a", json::array(), json::array({deviceJson("g", "source.solid_color")})),
        trackJson("b", json::array(), json::array({deviceJson("inv", "color.invert")})),
    }));
    c["routes"] = json::array({route("r1", portEnd("a", "__out__"), portEnd("b", "__in__"))});
    const auto b = buildOne(c, cat);
    const auto keys = chainKeys(b);
    CHECK(indexOf(keys, "track_b_in") < indexOf(keys, "clip_b_c_inv"));
    CHECK(findWire(b, "clip_b_c_inv", "clip_b_c_blend", "1").is_object());
  }
  SECTION("a track whose only content is its input") {
    json c = compOf(json::array({
        trackJson("a", json::array(), json::array({deviceJson("g", "source.solid_color")})),
        trackJson("b", json::array()),
    }));
    c["routes"] = json::array({route("r1", portEnd("a", "__out__"), portEnd("b", "__in__"))});
    const auto b = buildOne(c, cat);
    CHECK(findWire(b, "track_b_in", "track_b_blend", "1").is_object());
  }
}

TEST_CASE("io: a routed __in__ replaces a group's base", "[comp][io]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  json g = {{"id", "g"}, {"name", "g"}, {"kind", "group"}, {"parentId", nullptr},
            {"sketch", {{"devices", json::array()}}}, {"automation", json::array()},
            {"clips", json::array()}, {"groupInput", {{"mode", "underlying"}}}};
  json child = trackJson("k", json::array({deviceJson("inv", "color.invert")}));
  child["parentId"] = "g";
  json c = compOf(json::array({
      trackJson("a", json::array(), json::array({deviceJson("g1", "source.solid_color")})),
      g, child}));
  c["routes"] = json::array({route("r1", portEnd("a", "__out__"), portEnd("g", "__in__"))});
  const auto b = buildOne(c, cat);
  const auto keys = chainKeys(b);
  // The child processes the relay, and the group blends over the stack.
  CHECK(indexOf(keys, "track_g_in") < indexOf(keys, "track_k_inv"));
  CHECK(indexOf(keys, "group_g_blend") < keys.size());
}

TEST_CASE("io: send nowhere renders a track without compositing it", "[comp][io]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  SECTION("an adjustment layer after it processes the stack, not the hidden track") {
    json hidden = trackJson("h", json::array(), json::array({deviceJson("g", "source.noise")}),
                            {{"output", {{"mode", "none"}}}});
    json c = compOf(json::array({
        trackJson("a", json::array(), json::array({deviceJson("g", "source.solid_color")})),
        hidden,
        trackJson("adj", json::array({deviceJson("inv", "color.invert")})),
    }));
    const auto b = buildOne(c, cat);
    const auto keys = chainKeys(b);
    CHECK(indexOf(keys, "clip_h_c_g") < keys.size());   // it renders
    CHECK(indexOf(keys, "clip_h_c_blend") == keys.size());  // but never blends
    // A resync relay re-emits the stack before the adjustment reads it.
    const size_t resync = indexOf(keys, "io_resync_0");
    REQUIRE(resync < keys.size());
    CHECK(resync < indexOf(keys, "track_adj_inv"));
    CHECK(findWire(b, "clip_a_c_blend", "io_resync_0", "1").is_object());
  }
  SECTION("as the LAST layer, the output is re-emitted from the stack") {
    json hidden = trackJson("h", json::array(), json::array({deviceJson("g", "source.noise")}),
                            {{"output", {{"mode", "none"}}}});
    json c = compOf(json::array({
        trackJson("a", json::array(), json::array({deviceJson("g", "source.solid_color")})),
        hidden}));
    const auto b = buildOne(c, cat);
    const auto keys = chainKeys(b);
    REQUIRE(!keys.empty());
    CHECK(keys.back() == "io_resync_0");
  }
  SECTION("its routes still deliver") {
    json hidden = trackJson("h", json::array(), json::array({deviceJson("g", "source.noise")}),
                            {{"output", {{"mode", "none"}}}});
    json c = compOf(json::array({
        hidden, trackJson("b", json::array({deviceJson("inv", "color.invert")}))}));
    c["routes"] = json::array({route("r1", portEnd("h", "__out__"),
                                     fieldEnd("b", "", "inv", "mask"))});
    const auto b = buildOne(c, cat);
    CHECK(findWire(b, "clip_h_c_g", "track_b_inv", "mask").is_object());
  }
}

TEST_CASE("io: solo keeps a track that feeds a soloed one, sent nowhere", "[comp][io]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  json soloed = trackJson("s", json::array({deviceJson("inv", "color.invert")}));
  soloed["soloed"] = true;
  json c = compOf(json::array({
      trackJson("feed", json::array(), json::array({deviceJson("g", "source.noise")})),
      trackJson("other", json::array(), json::array({deviceJson("g", "source.solid_color")})),
      soloed}));
  c["routes"] = json::array({route("r1", portEnd("feed", "__out__"),
                                   fieldEnd("s", "", "inv", "mask"))});
  const auto b = buildOne(c, cat);
  const auto keys = chainKeys(b);
  CHECK(indexOf(keys, "clip_feed_c_g") < keys.size());      // kept for the route
  CHECK(indexOf(keys, "clip_feed_c_blend") == keys.size()); // but not composited
  CHECK(indexOf(keys, "clip_other_c_g") == keys.size());    // solo still drops the rest
  CHECK(findWire(b, "clip_feed_c_g", "track_s_inv", "mask").is_object());
}

TEST_CASE("io: inert and illegal routes", "[comp][io]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  json a = trackJson("a", json::array(), json::array({deviceJson("g", "source.solid_color")}));
  json bT = trackJson("b", json::array({deviceJson("inv", "color.invert")}));
  SECTION("a bypassed source leaves the route inert") {
    a["bypassed"] = true;
    json c = compOf(json::array({a, bT}));
    c["routes"] = json::array({route("r1", portEnd("a", "__out__"),
                                     fieldEnd("b", "", "inv", "mask"))});
    const auto b = buildOne(c, cat);
    CHECK(b.routeStatus["r1"]["live"] == false);
  }
  SECTION("field → field, __out__ as a destination, __in__ as a source") {
    json c = compOf(json::array({a, bT}));
    c["routes"] = json::array({
        route("x1", fieldEnd("a", "a_c", "g", "tex_out"), fieldEnd("b", "", "inv", "mask")),
        route("x2", portEnd("a", "__out__"), portEnd("b", "__out__")),
        route("x3", portEnd("a", "__in__"), fieldEnd("b", "", "inv", "mask")),
    });
    const auto b = buildOne(c, cat);
    CHECK_FALSE(b.routeStatus.contains("x1"));
    CHECK_FALSE(b.routeStatus.contains("x2"));
    CHECK_FALSE(b.routeStatus.contains("x3"));
    CHECK_FALSE(findWire(b, "clip_a_c_g", "track_b_inv").is_object());
  }
}
