// test_comp_build.cpp — replays the build.json goldens against the C++
// composition-executor ports: document parse (comp_model.h), effect catalog
// (comp_catalog.h), tree eval + automation (comp_eval.h), and the composite
// sketch build (sketch_build.h).
//
// The fixture is generated by the TS reference (web comp-goldens.test.ts,
// UPDATE_GOLDENS=1). For every (composition, beat) it snapshots the FULL built
// sketch JSON + the automation entries; this suite must reproduce them
// deep-equal. Deep-equal with a numeric tolerance: automation/rail-base values
// evaluate through the native float envelope.h (TS twin runs in double), and
// startSec goes through sin (~1 ulp) — everything else matches bit-exactly.

#include "sketch/comp/comp_catalog.h"
#include "sketch/comp/comp_eval.h"
#include "sketch/comp/comp_model.h"
#include "sketch/comp/sketch_build.h"
#include "sketch/comp/warp_curve.h"

#include <catch2/catch_test_macros.hpp>

#include <cmath>
#include <fstream>
#include <sstream>
#include <string>

#include <nlohmann/json.hpp>

using json = nlohmann::json;

namespace {

json loadFixture(const std::string& name) {
  const std::string path = std::string(COMP_FIXTURES_DIR) + "/" + name;
  std::ifstream f(path);
  REQUIRE(f.good());  // missing ⇒ run UPDATE_GOLDENS=1 npx vitest run comp-goldens (web/)
  json j = json::parse(f, nullptr, false);
  REQUIRE(!j.is_discarded());
  return j;
}

bool numbersClose(double a, double b) {
  const double diff = std::abs(a - b);
  return diff <= 1e-9 || diff <= 1e-6 * std::max(std::abs(a), std::abs(b));
}

/** Deep JSON equality with numeric tolerance; records the first divergence path. */
bool deepClose(const json& a, const json& b, std::string path, std::string& firstDiff) {
  if (a.is_number() && b.is_number()) {
    if (numbersClose(a.get<double>(), b.get<double>())) return true;
    firstDiff = path + ": " + a.dump() + " vs " + b.dump();
    return false;
  }
  if (a.type() != b.type()) {
    // null vs anything, object vs array, string vs number, bool mismatch...
    if (a == b) return true;
    firstDiff = path + ": type " + std::string(a.type_name()) + " vs " + b.type_name() +
                " (" + a.dump() + " vs " + b.dump() + ")";
    return false;
  }
  if (a.is_object()) {
    for (auto& [k, v] : a.items()) {
      if (!b.contains(k)) {
        firstDiff = path + "." + k + ": missing in expected";
        return false;
      }
      if (!deepClose(v, b[k], path + "." + k, firstDiff)) return false;
    }
    for (auto& [k, v] : b.items()) {
      if (!a.contains(k)) {
        firstDiff = path + "." + k + ": missing in actual";
        return false;
      }
    }
    return true;
  }
  if (a.is_array()) {
    if (a.size() != b.size()) {
      firstDiff = path + ": array size " + std::to_string(a.size()) + " vs " +
                  std::to_string(b.size());
      return false;
    }
    for (size_t i = 0; i < a.size(); i++) {
      if (!deepClose(a[i], b[i], path + "[" + std::to_string(i) + "]", firstDiff)) return false;
    }
    return true;
  }
  if (a == b) return true;
  firstDiff = path + ": " + a.dump() + " vs " + b.dump();
  return false;
}

void checkDeepClose(const json& actual, const json& expected, const std::string& what) {
  std::string firstDiff;
  const bool ok = deepClose(actual, expected, what, firstDiff);
  INFO(firstDiff);
  CHECK(ok);
}

}  // namespace

TEST_CASE("build goldens — tree eval + sketch build + automation match TS", "[comp]") {
  const json fx = loadFixture("build.json");

  comp::Catalog cat;
  for (const auto& p : fx["plugins"]) {
    cat.registerSchema(p["id"].get<std::string>(), p["schema"]);
    cat.registerCapabilities(p["id"].get<std::string>(), p["capabilities"]);
  }

  for (const auto& c : fx["cases"]) {
    const std::string name = c["name"].get<std::string>();
    INFO("case " << name);
    const comp::CompositionM comp = comp::parseComposition(c["composition"]);
    const bool ignoreSolo = c.value("ignoreSolo", false);
    const bool clipLoopMode = c.value("clipAutoTiming", std::string("loop")) == "loop";

    // The live path's cached clock: makeWarpClock(composition).
    const comp::WarpClock clock(
        comp::WarpCurve(comp::derivedWarpSegments(comp), comp::compositionLengthBeats(comp)),
        comp.baseBPM);

    for (const auto& frame : c["frames"]) {
      const double beat = frame["beat"].get<double>();
      INFO("beat " << beat);

      const auto build = comp::buildCompositeRenderAtBeat(comp, cat, clock, beat, ignoreSolo);
      if (frame["sketch"].is_null()) {
        CHECK(!build.hasContent);
      } else {
        REQUIRE(build.hasContent);
        checkDeepClose(build.sketch, frame["sketch"], "sketch");
      }

      const json automation = comp::automationEntriesAtBeat(comp, beat, ignoreSolo, clipLoopMode);
      checkDeepClose(automation, frame["automation"], "automation");
    }
  }
}
