// test_comp_build.cpp — replays the build.json goldens against the C++
// composition-executor ports: document parse (comp_model.h), effect catalog
// (comp_catalog.h), tree eval + automation (comp_eval.h), and the composite
// sketch build (sketch_build.h).
//
// The fixture is generated by the TS reference (web comp-goldens.test.ts,
// UPDATE_GOLDENS=1). For every (composition, beat) it snapshots the FULL built
// sketch JSON + the automation entries; this suite must reproduce them
// deep-equal. Deep-equal with a numeric tolerance: automation/rail-base values
// evaluate through the native float envelope.h (TS twin runs in double), and
// startSec goes through sin (~1 ulp) — everything else matches bit-exactly.

#include "sketch/comp/comp_catalog.h"
#include "sketch/comp/comp_eval.h"
#include "sketch/comp/comp_model.h"
#include "sketch/comp/sketch_build.h"
#include "sketch/comp/warp_curve.h"

#include <catch2/catch_test_macros.hpp>

#include <cmath>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

using json = nlohmann::json;

namespace {

json loadFixture(const std::string& name) {
  const std::string path = std::string(COMP_FIXTURES_DIR) + "/" + name;
  std::ifstream f(path);
  REQUIRE(f.good());  // missing ⇒ run UPDATE_GOLDENS=1 npx vitest run comp-goldens (web/)
  json j = json::parse(f, nullptr, false);
  REQUIRE(!j.is_discarded());
  return j;
}

bool numbersClose(double a, double b) {
  const double diff = std::abs(a - b);
  return diff <= 1e-9 || diff <= 1e-6 * std::max(std::abs(a), std::abs(b));
}

/** Deep JSON equality with numeric tolerance; records the first divergence path. */
bool deepClose(const json& a, const json& b, std::string path, std::string& firstDiff) {
  if (a.is_number() && b.is_number()) {
    if (numbersClose(a.get<double>(), b.get<double>())) return true;
    firstDiff = path + ": " + a.dump() + " vs " + b.dump();
    return false;
  }
  if (a.type() != b.type()) {
    // null vs anything, object vs array, string vs number, bool mismatch...
    if (a == b) return true;
    firstDiff = path + ": type " + std::string(a.type_name()) + " vs " + b.type_name() +
                " (" + a.dump() + " vs " + b.dump() + ")";
    return false;
  }
  if (a.is_object()) {
    for (auto& [k, v] : a.items()) {
      if (!b.contains(k)) {
        firstDiff = path + "." + k + ": missing in expected";
        return false;
      }
      if (!deepClose(v, b[k], path + "." + k, firstDiff)) return false;
    }
    for (auto& [k, v] : b.items()) {
      if (!a.contains(k)) {
        firstDiff = path + "." + k + ": missing in actual";
        return false;
      }
    }
    return true;
  }
  if (a.is_array()) {
    if (a.size() != b.size()) {
      firstDiff = path + ": array size " + std::to_string(a.size()) + " vs " +
                  std::to_string(b.size());
      return false;
    }
    for (size_t i = 0; i < a.size(); i++) {
      if (!deepClose(a[i], b[i], path + "[" + std::to_string(i) + "]", firstDiff)) return false;
    }
    return true;
  }
  if (a == b) return true;
  firstDiff = path + ": " + a.dump() + " vs " + b.dump();
  return false;
}

void checkDeepClose(const json& actual, const json& expected, const std::string& what) {
  std::string firstDiff;
  const bool ok = deepClose(actual, expected, what, firstDiff);
  INFO(firstDiff);
  CHECK(ok);
}

/** Register the shared plugin catalog (schemas + capabilities) from build.json. */
comp::Catalog catalogFrom(const json& fx) {
  comp::Catalog cat;
  for (const auto& p : fx["plugins"]) {
    cat.registerSchema(p["id"].get<std::string>(), p["schema"]);
    cat.registerCapabilities(p["id"].get<std::string>(), p["capabilities"]);
  }
  return cat;
}

/** Replay one fixture's `cases` array against the C++ build. */
void replayCases(const json& cases, const comp::Catalog& cat) {
  for (const auto& c : cases) {
    const std::string name = c["name"].get<std::string>();
    INFO("case " << name);
    const comp::CompositionM comp = comp::parseComposition(c["composition"]);
    const bool ignoreSolo = c.value("ignoreSolo", false);
    const bool clipLoopMode = c.value("clipAutoTiming", std::string("loop")) == "loop";

    // The live path's cached clock: makeWarpClock(composition).
    const comp::WarpClock clock(
        comp::WarpCurve(comp::derivedWarpSegments(comp), comp::compositionLengthBeats(comp)),
        comp.baseBPM);

    for (const auto& frame : c["frames"]) {
      const double beat = frame["beat"].get<double>();
      INFO("beat " << beat);

      const auto build = comp::buildCompositeRenderAtBeat(comp, cat, clock, beat, ignoreSolo);
      if (frame["sketch"].is_null()) {
        CHECK(!build.hasContent);
      } else {
        REQUIRE(build.hasContent);
        checkDeepClose(build.sketch, frame["sketch"], "sketch");
      }

      const json automation = comp::automationEntriesAtBeat(comp, beat, ignoreSolo, clipLoopMode);
      checkDeepClose(automation, frame["automation"], "automation");
    }
  }
}

}  // namespace

TEST_CASE("build goldens — tree eval + sketch build + automation match TS", "[comp]") {
  const json fx = loadFixture("build.json");
  replayCases(fx["cases"], catalogFrom(fx));
}

// The sequence cases live in their OWN fixture: build.json is frozen and its
// key order is the TS reference's insertion order, which nlohmann's writer does
// not preserve — regenerating in place would rewrite all 12 existing cases for
// no reason. Same plugin catalog, same replay.
TEST_CASE("build goldens — sequence clips", "[comp][comp_sequence]") {
  const json seq = loadFixture("build-sequence.json");
  replayCases(seq["cases"], catalogFrom(loadFixture("build.json")));
}

// ─────────────────────────────────────────────────────────────────────────────
// SEQUENCE-CLIP golden generator.
//
// The original TS reference (clip-sketch.ts / composite-frame.ts) was deleted
// when the offline exporter moved onto the comp executor, so there is no
// cross-host oracle left to generate a composite golden from. These cases are
// therefore CHANGE DETECTORS, not cross-validation — they pin the exact node
// structure, instance keys and wire numbering that compositeSequence emits
// today, so a refactor that silently renumbers wires or reorders the interior
// (the class the foldClipModulation extraction risked) fails loudly instead of
// quietly changing every user's render.
//
// Regenerate deliberately, and READ THE DIFF before committing:
//     ./build/test_comp_build "[.gen]"
// Hidden by the leading dot — the normal run replays them like any other case.
// ─────────────────────────────────────────────────────────────────────────────

namespace {

json gDevice(const std::string& id, const std::string& type, json state = json::object()) {
  json d = {{"id", id}, {"moduleType", type}, {"name", type}, {"capabilities", json::array()}};
  if (!state.empty()) d["state"] = std::move(state);
  return d;
}

json gClip(const std::string& id, double startBeat, double lengthBeat, json devices,
           json over = json::object()) {
  json c = {{"id", id}, {"name", id}, {"startBeat", startBeat}, {"lengthBeat", lengthBeat},
            {"kind", "effect"}, {"sketch", {{"devices", std::move(devices)}}},
            {"loop", {{"mode", "time"}, {"startSec", 0}, {"speed", 1},
                      {"direction", "forward"}}},
            {"automation", json::array()}, {"exports", json::array()},
            {"warps", json::array()}};
  c.update(over);
  return c;
}

json gTrack(const std::string& id, json clips, json over = json::object()) {
  json t = {{"id", id}, {"name", id}, {"kind", "track"}, {"parentId", nullptr},
            {"sketch", {{"devices", json::array()}}}, {"automation", json::array()},
            {"clips", std::move(clips)}};
  t.update(over);
  return t;
}

json gComposition(json tracks) {
  return {{"meta", {{"resolution", {{"width", 1920}, {"height", 1080}}},
                    {"baseBPM", 120}, {"timeSignature", json::array({4, 4})}}},
          {"tracks", std::move(tracks)}, {"rails", json::array()}};
}

/** A sequence clip: `laneDevices` is the interior lane's FX bus, `ownDevices`
 *  the sequence clip's own chain (which runs OVER the interior composite). */
json gSequenceClip(const std::string& id, double startBeat, double lengthBeat,
                   const std::string& laneId, json subClips, json ownDevices,
                   json laneDevices = json::array(), json ownWires = json::array()) {
  json lane = {{"id", laneId}, {"name", laneId}, {"kind", "track"}, {"parentId", nullptr},
               {"sketch", {{"devices", std::move(laneDevices)}}},
               {"automation", json::array()}, {"clips", std::move(subClips)}};
  json over = {{"kind", "sequence"}, {"sequence", std::move(lane)}};
  json c = gClip(id, startBeat, lengthBeat, std::move(ownDevices), over);
  if (!ownWires.empty()) c["sketch"]["wires"] = std::move(ownWires);
  return c;
}

/** Snapshot (sketch, automation) at each beat — the frame shape build.json uses. */
json gFrames(const comp::CompositionM& comp, const comp::Catalog& cat,
             const std::vector<double>& beats) {
  const comp::WarpClock clock(
      comp::WarpCurve(comp::derivedWarpSegments(comp), comp::compositionLengthBeats(comp)),
      comp.baseBPM);
  json frames = json::array();
  for (const double beat : beats) {
    const auto build = comp::buildCompositeRenderAtBeat(comp, cat, clock, beat, false);
    frames.push_back({{"beat", beat},
                      {"sketch", build.hasContent ? build.sketch : json()},
                      {"automation", comp::automationEntriesAtBeat(comp, beat, false, true)}});
  }
  return frames;
}

}  // namespace

TEST_CASE("[.gen] regenerate build-sequence.json", "[.gen]") {
  const std::string path = std::string(COMP_FIXTURES_DIR) + "/build-sequence.json";
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));

  json cases = json::array();

  // sequence-basic — the whole four-level stack in one case: interior sub-clip
  // → interior lane FX bus → the sequence clip's OWN chain → the parent track's
  // blend, over a second track so the blend-up has something to land on. Beats
  // 1 and 5 straddle the interior switch; beat 9 is past the sequence entirely
  // (the parent track must fall back to contributing nothing).
  {
    json comp = gComposition(json::array({
        gTrack("t1", json::array({gSequenceClip(
                   "seq", 0, 8, "lane1",
                   json::array({gClip("sub1", 0, 4,
                                      json::array({gDevice("sc", "source.solid_color")})),
                                gClip("sub2", 4, 4,
                                      json::array({gDevice("nz", "source.noise")}))}),
                   json::array({gDevice("sat", "color.saturate")}),
                   json::array({gDevice("linv", "color.invert")}))}),
               {{"level", 0.8}}),
        gTrack("t2", json::array({gClip("base", 0, 16,
                                        json::array({gDevice("bn", "source.noise")}))})),
    }));
    cases.push_back({{"name", "sequence-basic"},
                     {"composition", comp},
                     {"frames", gFrames(comp::parseComposition(comp), cat, {1, 5, 9})}});
  }

  // sequence-underlying-seed — the interior seeds from `underlying`, NOT from a
  // transparent input: an interior holding ONLY an effect must process the
  // track below it. Also pins clip-modulation wire numbering on both levels at
  // once (an LFO inside the sub-clip AND one on the sequence clip's own chain),
  // which is what keeps compositeSequence and compositeClip from drifting.
  {
    json subWires = json::array({{{"id", "w1"},
                                  {"src", {{"instanceKey", "slfo"}, {"field", "output"}}},
                                  {"dest", {{"instanceKey", "ssat"}, {"field", "prescale"}}},
                                  {"combine", "add"},
                                  {"magnitude", "signed"}}});
    json ownWires = json::array({{{"id", "w2"},
                                  {"src", {{"instanceKey", "olfo"}, {"field", "output"}}},
                                  {"dest", {{"instanceKey", "osat"}, {"field", "prescale"}}},
                                  {"combine", "add"},
                                  {"magnitude", "signed"}}});
    json sub = gClip("fxonly", 0, 8,
                     json::array({gDevice("ssat", "color.saturate"),
                                  gDevice("slfo", "mod.source.lfo",
                                          {{"rate", 0.25}})}));
    sub["sketch"]["wires"] = subWires;
    json comp = gComposition(json::array({
        gTrack("t1", json::array({gSequenceClip(
                   "seq", 0, 8, "lane1", json::array({sub}),
                   json::array({gDevice("osat", "color.saturate"),
                                gDevice("olfo", "mod.source.lfo", {{"rate", 0.5}})}),
                   json::array(), ownWires)})),
        gTrack("t2", json::array({gClip("under", 0, 16,
                                        json::array({gDevice("un", "source.noise")}))})),
    }));
    cases.push_back({{"name", "sequence-underlying-seed"},
                     {"composition", comp},
                     {"frames", gFrames(comp::parseComposition(comp), cat, {2})}});
  }

  std::ofstream out(path);
  REQUIRE(out.good());
  out << json{{"cases", std::move(cases)}}.dump(1) << "\n";
  WARN("regenerated " << path << " — READ THE DIFF");
}

// ─────────────────────────────────────────────────────────────────────────────
// MULTIPLE SOURCES IN ONE CLIP.
//
// The build used to keep only the FIRST generator in a clip's chain and drop
// every later one, so a second source (two source.text.plain with different
// copy, say) simply never rendered. The first generator still ANCHORS the layer;
// the rest follow it in declaration order, so a source that reads tex_in
// composites over what came before and one that ignores it wins outright.
namespace {

/** A one-track composition whose single clip carries `devices` in order. */
json compWithDevices(const std::vector<std::pair<std::string, std::string>>& devices) {
  json devs = json::array();
  for (const auto& [id, type] : devices) {
    devs.push_back({{"id", id}, {"moduleType", type}, {"name", type},
                    {"capabilities", json::array()}, {"state", json::object()}});
  }
  return {
    {"meta", {{"resolution", {{"width", 64}, {"height", 64}}},
              {"baseBPM", 120}, {"timeSignature", {4, 4}}}},
    {"tracks", json::array({
      {{"id", "t1"}, {"name", "t1"}, {"kind", "track"}, {"parentId", nullptr},
       {"sketch", {{"devices", json::array()}}}, {"automation", json::array()},
       {"clips", json::array({
         {{"id", "c1"}, {"name", "c1"}, {"startBeat", 0}, {"lengthBeat", 8},
          {"kind", "effect"}, {"sketch", {{"devices", devs}}},
          {"automation", json::array()}, {"exports", json::array()},
          {"warps", json::array()}, {"blendMode", 0}}})}},
    })},
    {"rails", json::array()},
  };
}

/** Ordered `instance_key`s of the built chain. */
std::vector<std::string> chainKeys(const comp::SketchBuild& b) {
  std::vector<std::string> out;
  for (const auto& e : b.sketch["chain"]) out.push_back(e.value("instance_key", std::string()));
  return out;
}

comp::SketchBuild buildOne(const json& compJson, const comp::Catalog& cat) {
  const comp::CompositionM c = comp::parseComposition(compJson);
  const comp::WarpClock clock(
      comp::WarpCurve(comp::derivedWarpSegments(c), comp::compositionLengthBeats(c)), c.baseBPM);
  return comp::buildCompositeRenderAtBeat(c, cat, clock, 0.0, false);
}

}  // namespace

TEST_CASE("a clip's SECOND generator stays in the chain", "[comp]") {
  const comp::Catalog cat = catalogFrom(loadFixture("build.json"));
  REQUIRE(cat.isGenerator("source.solid_color"));
  REQUIRE(cat.isGenerator("source.noise"));

  SECTION("two sources render in declaration order, the first anchoring the layer") {
    const auto b = buildOne(compWithDevices({{"g1", "source.solid_color"},
                                             {"g2", "source.noise"}}), cat);
    REQUIRE(b.hasContent);
    const auto keys = chainKeys(b);
    // arr_bg is the opaque backdrop under all clips, clip_c1_blend composites the
    // layer over it; between them the clip's own devices, in order.
    CHECK(keys == std::vector<std::string>{
        "arr_bg", "clip_c1_g1", "clip_c1_g2", "clip_c1_blend"});
  }

  SECTION("effects between two sources keep their order relative to each other") {
    const auto b = buildOne(compWithDevices({{"g1", "source.solid_color"},
                                             {"fx", "color.invert"},
                                             {"g2", "source.noise"}}), cat);
    REQUIRE(b.hasContent);
    const auto keys = chainKeys(b);
    CHECK(keys == std::vector<std::string>{
        "arr_bg", "clip_c1_g1", "clip_c1_fx", "clip_c1_g2", "clip_c1_blend"});
  }

  SECTION("a generator that is not first is still hoisted to anchor the layer") {
    // [fx, gen] must not start the chain on an effect — there would be nothing
    // to process. The generator leads; the effect follows it (the pre-existing
    // rule, unchanged).
    const auto b = buildOne(compWithDevices({{"fx", "color.invert"},
                                             {"g1", "source.noise"}}), cat);
    REQUIRE(b.hasContent);
    const auto keys = chainKeys(b);
    CHECK(keys == std::vector<std::string>{
        "arr_bg", "clip_c1_g1", "clip_c1_fx", "clip_c1_blend"});
  }
}
