// test_video_policy.cpp — replays the video-policy goldens against the C++
// ports in native/src/media/.
//
// The fixtures are generated by the TS reference
// (web/src/video/video-policy-goldens.test.ts, UPDATE_GOLDENS=1). Every
// scenario is fully scripted — the pull lists, the cache op lists and the
// injected clock all live IN the fixture — so this replay needs no RNG and no
// wall clock, and a divergence here is a real divergence in policy.
//
// This is the lock-step contract for:
//   access_classifier.h  ↔ web/src/video/access-classifier.ts
//   cost_tracker.h       ↔ web/src/video/cost-tracker.ts
//   read_ahead.h         ↔ web/src/video/read-ahead.ts
//   frame_cache_policy.h ↔ web/src/video/frame-cache.ts
//
// Numeric tolerance: modes/classes/handles/indices must match EXACTLY; only
// the confidence and EWMA doubles get a tolerance, because Math.exp/Math.sqrt
// can differ from libm by ~1 ulp.

#include <catch2/catch_test_macros.hpp>

#include <cmath>
#include <fstream>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

#include "media/access_classifier.h"
#include "media/cost_tracker.h"
#include "media/frame_cache_policy.h"
#include "media/read_ahead.h"

using json = nlohmann::json;
using namespace nano_media;

namespace {

json loadFixture(const std::string& name) {
  const std::string path = std::string(VIDEO_FIXTURES_DIR) + "/" + name;
  std::ifstream f(path);
  // Missing ⇒ run UPDATE_GOLDENS=1 npx vitest run video-policy-goldens (web/).
  REQUIRE(f.good());
  json j = json::parse(f, nullptr, false);
  REQUIRE(!j.is_discarded());
  return j;
}

bool close(double a, double b) {
  const double d = std::abs(a - b);
  return d <= 1e-9 || d <= 1e-9 * std::max(std::abs(a), std::abs(b));
}

std::vector<int> intVec(const json& j) {
  std::vector<int> out;
  for (const auto& v : j) out.push_back(v.get<int>());
  return out;
}

std::string join(const std::vector<int>& v) {
  std::string s;
  for (std::size_t i = 0; i < v.size(); i++) {
    if (i) s += ",";
    s += std::to_string(v[i]);
  }
  return s;
}

}  // namespace

TEST_CASE("read-ahead targets + pin sets match the TS policy", "[video_policy]") {
  const json fx = loadFixture("read-ahead.json");
  CHECK(fx["depth"].get<int>() == kReadAheadDepth);

  for (const auto& c : fx["targets"]) {
    ReadAheadInputs inp;
    inp.mode = accessModeFromName(c["mode"].get<std::string>());
    inp.frameIdx = c["frameIdx"].get<int>();
    inp.frameCount = c["frameCount"].get<int>();
    inp.motionDir = c.value("motionDir", 1);
    inp.depth = c["depth"].get<int>();
    if (c.contains("stride") && c["stride"].is_number()) {
      inp.hasStride = true;
      inp.stride = c["stride"].get<int>();
    }
    const std::vector<int> got = computeReadAheadTargets(inp);
    const std::vector<int> want = intVec(c["expect"]);
    INFO(c.dump() << "\n got [" << join(got) << "]");
    CHECK(got == want);
  }

  for (const auto& c : fx["pinned"]) {
    ClassifierSnapshot snap;
    snap.mode = accessModeFromName(c["mode"].get<std::string>());
    snap.confidence = c.value("confidence", 0.0);
    if (c.contains("loopRange")) {
      snap.hasLoopRange = true;
      snap.loopRangeA = c["loopRange"][0].get<int>();
      snap.loopRangeB = c["loopRange"][1].get<int>();
    }
    if (c.contains("hotFrames")) {
      snap.hasHotFrames = true;
      snap.hotFrames = intVec(c["hotFrames"]);
    }
    const std::vector<int> got = computePinnedFrames(snap);
    INFO(c.dump() << "\n got [" << join(got) << "]");
    CHECK(got == intVec(c["expect"]));
  }
}

TEST_CASE("the access classifier reproduces every scripted pull stream", "[video_policy]") {
  const json fx = loadFixture("classifier.json");
  REQUIRE(fx.is_array());
  REQUIRE(!fx.empty());

  for (const auto& scenario : fx) {
    const std::string name = scenario["name"].get<std::string>();
    AccessClassifier c;
    const auto& pulls = scenario["pulls"];
    const auto& want = scenario["snapshots"];
    REQUIRE(pulls.size() == want.size());

    for (std::size_t i = 0; i < pulls.size(); i++) {
      c.recordPull(pulls[i][0].get<int>(), pulls[i][1].get<double>());
      const ClassifierSnapshot got = c.snapshot();
      const auto& w = want[i];

      INFO(name << " pull #" << i << " frame " << pulls[i][0]
                << ": got " << accessModeName(got.mode) << " (" << got.confidence
                << "), want " << w["mode"] << " (" << w["confidence"] << ")");
      CHECK(std::string(accessModeName(got.mode)) == w["mode"].get<std::string>());
      CHECK(close(got.confidence, w["confidence"].get<double>()));

      // `null` in the fixture is TS `undefined` — the extra doesn't apply to
      // this mode. Presence is part of the contract, not just the value.
      CHECK(got.hasStride == !w["stride"].is_null());
      if (got.hasStride) CHECK(got.stride == w["stride"].get<int>());

      CHECK(got.hasLoopRange == !w["loopRange"].is_null());
      if (got.hasLoopRange) {
        CHECK(got.loopRangeA == w["loopRange"][0].get<int>());
        CHECK(got.loopRangeB == w["loopRange"][1].get<int>());
      }

      CHECK(got.hasHotFrames == !w["hotFrames"].is_null());
      if (got.hasHotFrames) CHECK(got.hotFrames == intVec(w["hotFrames"]));
    }

    // …and the policy pair the final mode drives.
    const ClassifierSnapshot fin = c.snapshot();
    const int lastIdx = pulls[pulls.size() - 1][0].get<int>();
    const int prevIdx = pulls.size() >= 2 ? pulls[pulls.size() - 2][0].get<int>() : lastIdx;
    ReadAheadInputs inp;
    inp.mode = fin.mode;
    inp.frameIdx = lastIdx;
    inp.frameCount = 1000;
    inp.motionDir = (lastIdx - prevIdx) < 0 ? -1 : 1;
    inp.depth = kReadAheadDepth;
    inp.hasStride = fin.hasStride;
    inp.stride = fin.stride;
    INFO(name << " read-ahead");
    CHECK(computeReadAheadTargets(inp) == intVec(scenario["readAhead"]));
    INFO(name << " pinned");
    CHECK(computePinnedFrames(fin) == intVec(scenario["pinned"]));
  }
}

namespace {

CostPullOpts pullFrom(const json& j) {
  CostPullOpts o;
  o.stride = j["stride"].get<int>();
  o.decodeMs = j["decodeMs"].get<double>();
  if (j.contains("firstByteMs")) {
    o.hasFirstByteMs = true;
    o.firstByteMs = j["firstByteMs"].get<double>();
  }
  if (j.contains("payloadBytes")) {
    o.hasPayloadBytes = true;
    o.payloadBytes = j["payloadBytes"].get<double>();
  }
  return o;
}

void checkCostSnapshot(const std::string& where, const CostSnapshot& got, const json& w) {
  INFO(where << ": got class " << costClassName(got.costClass) << " mean " << got.meanFrameDecodeMs
             << " seek " << got.seekDecodeMs << ", want " << w.dump());
  CHECK(std::string(costClassName(got.costClass)) == w["costClass"].get<std::string>());
  CHECK(close(got.meanFrameDecodeMs, w["meanFrameDecodeMs"].get<double>()));
  CHECK(close(got.seekDecodeMs, w["seekDecodeMs"].get<double>()));
  CHECK(close(got.seekPenaltyMs, w["seekPenaltyMs"].get<double>()));
  CHECK(close(got.firstByteLatencyMs, w["firstByteLatencyMs"].get<double>()));
  CHECK(close(got.payloadBytesPerFrame, w["payloadBytesPerFrame"].get<double>()));
  CHECK(got.samples == w["samples"].get<int>());
  CHECK(got.contiguousSamples == w["contiguousSamples"].get<int>());
  CHECK(got.seekSamples == w["seekSamples"].get<int>());
}

}  // namespace

TEST_CASE("the cost tracker reproduces every EWMA scenario", "[video_policy]") {
  const json fx = loadFixture("cost.json");

  for (const auto& scenario : fx["scenarios"]) {
    const std::string name = scenario["name"].get<std::string>();
    CostTracker t;
    const auto& pulls = scenario["pulls"];
    const auto& want = scenario["snapshots"];
    REQUIRE(pulls.size() == want.size());
    for (std::size_t i = 0; i < pulls.size(); i++) {
      t.recordPull(pullFrom(pulls[i]));
      checkCostSnapshot(name + " pull #" + std::to_string(i), t.snapshot(), want[i]);
    }
  }

  // Seeding from a persisted profile, then two live pulls.
  {
    const auto& s = fx["seeded"];
    CostSnapshot seed;
    seed.meanFrameDecodeMs = s["seed"]["meanFrameDecodeMs"].get<double>();
    seed.seekDecodeMs = s["seed"]["seekDecodeMs"].get<double>();
    seed.firstByteLatencyMs = s["seed"]["firstByteLatencyMs"].get<double>();
    seed.payloadBytesPerFrame = s["seed"]["payloadBytesPerFrame"].get<double>();
    seed.samples = s["seed"]["samples"].get<int>();
    CostTracker t;
    t.seedFromPersisted(seed);
    checkCostSnapshot("seeded #0", t.snapshot(), s["snapshots"][0]);
    for (std::size_t i = 0; i < s["pulls"].size(); i++) {
      t.recordPull(pullFrom(s["pulls"][i]));
      checkCostSnapshot("seeded #" + std::to_string(i + 1), t.snapshot(), s["snapshots"][i + 1]);
    }
  }

  // Direct threshold probes.
  for (const auto& c : fx["classify"]) {
    const CostClass got = classifyCost(c["samples"].get<int>(), c["meanDecode"].get<double>(),
                                       c["seekDecode"].get<double>());
    INFO(c.dump() << " got " << costClassName(got));
    CHECK(std::string(costClassName(got)) == c["expect"].get<std::string>());
  }
}

namespace {

/// Hands out sequential handles and logs every release — the fixture pins
/// WHICH texture was freed and in what order, which IS the eviction contract.
struct FakePool : TexturePool {
  int next = 1;
  std::vector<int> released;
  int createTexture(int, int, int) override { return next++; }
  void release(int handle) override { released.push_back(handle); }
};

void checkCacheStats(const std::string& where, const FrameCacheStats& got, const json& w) {
  INFO(where << ": got bytes " << got.bytes << " entries " << got.entries << " hits " << got.hits
             << " misses " << got.misses << ", want " << w.dump());
  CHECK(got.bytes == w["bytes"].get<long long>());
  CHECK(got.entries == w["entries"].get<int>());
  CHECK(got.hits == w["hits"].get<int>());
  CHECK(got.misses == w["misses"].get<int>());
  CHECK(close(got.hitRate, w["hitRate"].get<double>()));
  CHECK(got.recentHits == w["recentHits"].get<int>());
  CHECK(got.recentMisses == w["recentMisses"].get<int>());
  CHECK(close(got.recentHitRate, w["recentHitRate"].get<double>()));
  CHECK(got.pinnedEvicted == w["pinnedEvicted"].get<bool>());
}

}  // namespace

TEST_CASE("the frame cache reproduces every residency + eviction script", "[video_policy]") {
  const json fx = loadFixture("cache.json");
  REQUIRE(fx.is_array());

  for (const auto& scenario : fx) {
    const std::string name = scenario["name"].get<std::string>();
    FakePool pool;
    double clock = 0;
    FrameCachePolicy cache(&pool, scenario["budgetBytes"].get<long long>(),
                           [&clock]() { return clock; }, 1000);

    const auto& ops = scenario["ops"];
    const auto& trace = scenario["result"]["trace"];
    REQUIRE(ops.size() == trace.size());

    for (std::size_t i = 0; i < ops.size(); i++) {
      const auto& o = ops[i];
      const auto& w = trace[i];
      const std::string op = o["op"].get<std::string>();
      const std::string where = name + " op #" + std::to_string(i) + " (" + op + ")";
      REQUIRE(w["op"].get<std::string>() == op);

      if (op == "reserve") {
        const int handle = cache.reserve(o["frame"].get<int>(), o["width"].get<int>(),
                                         o["height"].get<int>(), o["format"].get<int>());
        INFO(where << ": handle " << handle);
        CHECK(handle == w["handle"].get<int>());
      } else if (op == "markReady") {
        cache.markReady(o["frame"].get<int>());
      } else if (op == "lookup") {
        const int handle = cache.lookup(o["frame"].get<int>());
        INFO(where << " frame " << o["frame"] << ": handle " << handle);
        CHECK(handle == w["handle"].get<int>());
      } else if (op == "setPinned") {
        cache.setPinned(intVec(o["frames"]));
        INFO(where);
        CHECK(cache.pinnedFrameIndices() == intVec(w["pinned"]));
      } else if (op == "advance") {
        clock += o["ms"].get<double>();
        CHECK(close(clock, w["clock"].get<double>()));
      } else if (op == "stats") {
        checkCacheStats(where, cache.stats(), w["stats"]);
        INFO(where << " cached");
        CHECK(cache.cachedFrameIndices() == intVec(w["cached"]));
      } else if (op == "resetStats") {
        cache.resetStats();
      } else if (op == "clear") {
        cache.clear();
      } else {
        FAIL("unknown cache op: " << op);
      }
    }

    const auto& result = scenario["result"];
    INFO(name << " released order");
    CHECK(pool.released == intVec(result["released"]));
    INFO(name << " final residency");
    CHECK(cache.cachedFrameIndices() == intVec(result["cached"]));
    CHECK(cache.currentBytes() == result["bytes"].get<long long>());
    checkCacheStats(name + " final", cache.stats(), result["stats"]);
  }
}
