/**
 * streams-registry.test.ts — the web StreamsRegistry replays the SAME golden
 * the native registry produced (native/tests/fixtures/comp/streams-golden.json,
 * regenerated by NANO_UPDATE_GOLDENS=1 ./test_streams_abi). Assertion values
 * mirror native/tests/test_streams_abi.cpp — that pair is the lock-step
 * contract for the seekable-streams surface (streams_table.h evaluators ↔
 * StreamsRegistry methods ↔ both hosts' streams.* imports).
 */
import { describe, it, expect, beforeEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { StreamsRegistry, StreamKind, StreamFlags } from './streams-registry';

const GOLDEN = path.resolve(
  __dirname, '../../native/tests/fixtures/comp/streams-golden.json');

// The fixture doc is unwarped at 120 BPM → 0.5 s/beat (test_streams_abi build()).
const secondsAt = (beat: number) => beat * 0.5;

describe('StreamsRegistry (lock-step with streams_table.h)', () => {
  let reg: StreamsRegistry;
  let trackA: bigint;
  let scenes: bigint;

  beforeEach(() => {
    expect(fs.existsSync(GOLDEN),
      'streams-golden.json missing — run NANO_UPDATE_GOLDENS=1 ./build/test_streams_abi',
    ).toBe(true);
    reg = new StreamsRegistry();
    reg.loadStatic(JSON.parse(fs.readFileSync(GOLDEN, 'utf8')), secondsAt);
    trackA = reg.parentByClipId.get('clipA')!;
    scenes = reg.parentByClipId.get('s1')!;
  });

  it('mirrors the enumeration shape', () => {
    expect(reg.docRev).toBe(7);
    expect(reg.enumCount).toBe(4);
    expect(reg.streams[0].kind).toBe(StreamKind.SessionClock);
    expect(reg.streams[0].handle).toBe(1n);
    expect(reg.streams[1].kind).toBe(StreamKind.Timeline);
    expect(reg.streams[1].durationPrimary).toBe(64);
    expect(reg.streams[1].durationSec).toBe(32);
    const tA = reg.find(trackA)!;
    expect(tA.kind).toBe(StreamKind.TimelineTrack);
    expect(tA.name).toBe('Video A');
    expect(tA.clipCount).toBe(3);
    expect(tA.durationPrimary).toBe(16);
    const sc = reg.find(scenes)!;
    expect(sc.kind).toBe(StreamKind.SceneTrack);
    expect(sc.durationPrimary).toBe(3);
  });

  it('replays timeline-track events: grid order, stop-before-start ties', () => {
    const ev = reg.find(trackA)!.events;
    expect(ev.length).toBe(4);
    // [start A@0, stop A@8, start B@8, stop B@12] — clipC bypassed → no events.
    expect([ev[0].time, ev[0].kind, ev[0].clipOrdinal]).toEqual([0, 0, 0]);
    expect([ev[1].time, ev[1].kind, ev[1].clipOrdinal]).toEqual([8, 1, 0]);
    expect([ev[2].time, ev[2].kind, ev[2].clipOrdinal]).toEqual([8, 0, 1]);
    expect([ev[3].time, ev[3].kind, ev[3].clipOrdinal]).toEqual([12, 1, 1]);
    expect(ev[0].idHash48).not.toBe(ev[2].idHash48);
    expect(ev[0].idHash48).toBeLessThan(2 ** 48);
    expect(Number.isNaN(ev[0].channel)).toBe(true);
    // lower_bound cursor helper.
    expect(reg.eventLowerBound(reg.find(trackA)!, 8)).toBe(1);
    expect(reg.eventLowerBound(reg.find(trackA)!, 12.5)).toBe(4);
  });

  it('replays scene events: ordinal axis + lock-step channels, empty skipped', () => {
    const ev = reg.find(scenes)!.events;
    expect(ev.length).toBe(2);
    expect([ev[0].time, ev[0].clipOrdinal, ev[0].channel]).toEqual([0, 0, 3]);
    expect([ev[1].time, ev[1].clipOrdinal, ev[1].channel]).toEqual([1, 1, 1]);
  });

  it('classifies content streams and their seek cost', () => {
    const still = reg.find(reg.contentByClipId.get('clipA')!)!;
    expect(still.kind).toBe(StreamKind.VideoContent);
    expect(still.index).toBe(-1); // not enumerated
    expect(still.flags & StreamFlags.SeekInstant).toBeTruthy();
    const vid = reg.find(reg.contentByClipId.get('clipB')!)!;
    expect(vid.flags & StreamFlags.SeekSlow).toBeTruthy();
    expect(vid.frameCount).toBe(120);
    expect(vid.durationSec).toBe(4);
    expect(vid.anchorBeat).toBe(8);
  });

  it('evaluates content positions identically to native (lazy + override + still)', () => {
    const vid = reg.find(reg.contentByClipId.get('clipB')!)!;
    // 'time' mode anchored at beat 8: two beats past at 120 BPM = 1 real second.
    reg.frame.posBeat = 10;
    expect(reg.pos(vid, 0)).toBeCloseTo(1.0, 9);
    // A transport-controller override beats the built-in mapping.
    reg.appliedContentSec.set('clipB', 2.75);
    expect(reg.pos(vid, 0)).toBeCloseTo(2.75, 9);
    reg.appliedContentSec.clear();
    // A still shows source second 0 for its whole span.
    const still = reg.find(reg.contentByClipId.get('clipA')!)!;
    reg.frame.posBeat = 2;
    expect(reg.pos(still, 0)).toBeCloseTo(0, 9);
  });

  it('resolves effect self-scoping from instance keys (underscore-safe)', () => {
    expect(reg.clipIdForInstanceKey('clip_clipB_transport_dev1')).toBe('clipB');
    expect(reg.clipIdForInstanceKey('track_t1_dev')).toBe(null);
    expect(reg.parentOf('clip_clipB_vid')).toBe(trackA);
    expect(reg.contentOf('clip_clipB_vid')).toBe(reg.contentByClipId.get('clipB'));
    // Unknown keys fall back to the session clock / no content.
    expect(reg.parentOf('standalone')).toBe(1n);
    expect(reg.contentOf('standalone')).toBe(0n);
  });

  it('syncs launched scenes onto the ordinal axis + re-anchors content', () => {
    const sc = reg.find(scenes)!;
    expect(Number.isNaN(reg.pos(sc, 0))).toBe(true);
    expect(reg.playing(sc)).toBe(0);
    reg.frame.playing = 1;
    reg.frame.posBeat = 42;
    reg.frame.posSec = 21;
    reg.syncSceneLaunches({ scenes: { sceneId: 's2', launchBeat: 40 } } as any);
    // s2 is grid ordinal 1, lengthBeat 4: two beats in = fraction 0.5.
    expect(reg.pos(sc, 0)).toBeCloseTo(1.5, 9);
    expect(reg.posSec(sc, 0)).toBeCloseTo(21 - 40 * 0.5, 9);
    expect(reg.playing(sc)).toBe(1);
    // The launched scene's CONTENT stream re-anchored to the launch beat.
    expect(reg.find(reg.contentByClipId.get('s2')!)!.anchorBeat).toBe(40);
    // Stop: everything reverts to idle.
    reg.syncSceneLaunches({});
    expect(Number.isNaN(reg.pos(sc, 0))).toBe(true);
  });

  it('clip refs: standard duration, grid slots, ordinal lookup (golden values)', () => {
    const sc = reg.find(scenes)!;
    expect(sc.byOrdinalClipId).toEqual(['s1', 's2', 's3']);
    expect(reg.clipGrid(sc, 0)).toBe(0);
    expect(reg.clipGrid(sc, 1)).toBe(1);
    expect(reg.clipGrid(sc, 2)).toBe(2);
    // s2 video: 60f@30 → 2 s; s1 effect-only: 4 beats @120 → 2 s.
    expect(reg.clipDuration(sc, 1)).toBeCloseTo(2, 9);
    expect(reg.clipDuration(sc, 0)).toBeCloseTo(2, 9);
    expect(Number.isNaN(reg.clipDuration(sc, 99))).toBe(true);
    const tA = reg.find(trackA)!;
    expect(reg.clipDuration(tA, tA.clipsById.get('clipB')![0])).toBeCloseTo(4, 9);
  });

  it('scene-track pos() clamps strictly below the next ordinal', () => {
    const sc = reg.find(scenes)!;
    sc.liveOrdinal = 1;
    sc.liveAnchorBeat = 10;
    sc.liveLengthBeat = 4;
    reg.frame.posBeat = 100; // long-playing: way past the grid cell
    const pos = reg.pos(sc, 0);
    expect(pos).toBeLessThan(2);
    expect(Math.floor(pos)).toBe(1); // still THIS scene's ordinal
    reg.frame.posBeat = 10;
    expect(reg.pos(sc, 0)).toBeCloseTo(1, 12);
    // Ordinal 2 is the round-to-even trap: 2 + (1 - one ulp) rounds to 3.0 —
    // the clamp margin must survive the addition.
    sc.liveOrdinal = 2;
    reg.frame.posBeat = 100;
    expect(Math.floor(reg.pos(sc, 0))).toBe(2);
  });

  it('write verbs queue with validation (seek needs TriggerOnSeek; stop needs a scene track)', () => {
    expect(reg.queueSeek(scenes, 1.0)).toBe(true);       // scene track: trigger-on-seek
    expect(reg.queueSeek(trackA, 1.0)).toBe(true);       // timeline track carries the flag too
    expect(reg.queueSeek(reg.contentByClipId.get('clipB')!, 0)).toBe(false); // content: no
    expect(reg.queueStop(scenes)).toBe(true);
    expect(reg.queueStop(trackA)).toBe(false);           // stop is scene-only
    expect(reg.pendingOps.map((o) => o.kind)).toEqual(['seek', 'seek', 'stop']);
    expect(reg.pendingOps[0].handle).toBe(scenes);
  });

  it('live scene state survives a static reload (doc reloads are routine)', () => {
    const sc = reg.find(scenes)!;
    reg.frame.posBeat = 42;
    reg.syncSceneLaunches({ scenes: { sceneId: 's2', launchBeat: 40 } } as any);
    expect(Math.floor(reg.pos(sc, 0))).toBe(1);
    // A doc reload rebuilds every StreamRec — the launch map must re-apply
    // (the engine's launches survive reloads; the scenes channel only ships
    // on change, so a reload would otherwise strand live positions at NaN).
    reg.loadStatic(JSON.parse(fs.readFileSync(GOLDEN, 'utf8')), secondsAt);
    const sc2 = reg.find(scenes)!;
    expect(Math.floor(reg.pos(sc2, 0))).toBe(1);
    expect(reg.find(reg.contentByClipId.get('s2')!)!.anchorBeat).toBe(40);
  });

  it('reports loop regions per kind', () => {
    // Timeline loop brace rides the frame sample.
    reg.frame.loopEnabled = 1;
    reg.frame.loopStartBeat = 4;
    reg.frame.loopEndBeat = 12;
    expect(reg.loopRegion(reg.find(trackA)!)).toEqual([4, 12]);
    reg.frame.loopEnabled = 0;
    expect(reg.loopRegion(reg.find(trackA)!)).toBe(null);
    // A 'time'-mode content stream exposes its source slice.
    const vid = reg.find(reg.contentByClipId.get('clipB')!)!;
    expect(reg.loopRegion(vid)).toEqual([0, 4]);
    // Scene tracks and clocks have none.
    expect(reg.loopRegion(reg.find(scenes)!)).toBe(null);
    expect(reg.loopRegion(reg.streams[0])).toBe(null);
  });
});
