/**
 * streams-registry.test.ts — the web StreamsRegistry replays the SAME golden
 * the native registry produced (native/tests/fixtures/comp/streams-golden.json,
 * regenerated by NANO_UPDATE_GOLDENS=1 ./test_streams_abi). Assertion values
 * mirror native/tests/test_streams_abi.cpp — that pair is the lock-step
 * contract for the seekable-streams surface (streams_table.h evaluators ↔
 * StreamsRegistry methods ↔ both hosts' streams.* imports).
 */
import { describe, it, expect, beforeEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { StreamsRegistry, StreamKind, StreamFlags, ResourceKind, ResourceFlags,
         CONTENT_EVENT_HORIZON } from './streams-registry';

const GOLDEN = path.resolve(
  __dirname, '../../native/tests/fixtures/comp/streams-golden.json');

// The fixture doc is unwarped at 120 BPM → 0.5 s/beat (test_streams_abi build()).
const secondsAt = (beat: number) => beat * 0.5;

describe('StreamsRegistry (lock-step with streams_table.h)', () => {
  let reg: StreamsRegistry;
  let trackA: bigint;
  let scenes: bigint;

  beforeEach(() => {
    expect(fs.existsSync(GOLDEN),
      'streams-golden.json missing — run NANO_UPDATE_GOLDENS=1 ./build/test_streams_abi',
    ).toBe(true);
    reg = new StreamsRegistry();
    reg.loadStatic(JSON.parse(fs.readFileSync(GOLDEN, 'utf8')), secondsAt);
    trackA = reg.parentByClipId.get('clipA')!;
    scenes = reg.parentByClipId.get('s1')!;
  });

  it('mirrors the enumeration shape', () => {
    expect(reg.docRev).toBe(7);
    expect(reg.enumCount).toBe(4);
    expect(reg.streams[0].kind).toBe(StreamKind.SessionClock);
    expect(reg.streams[0].handle).toBe(1n);
    expect(reg.streams[1].kind).toBe(StreamKind.Timeline);
    expect(reg.streams[1].durationPrimary).toBe(64);
    expect(reg.streams[1].durationSec).toBe(32);
    const tA = reg.find(trackA)!;
    expect(tA.kind).toBe(StreamKind.TimelineTrack);
    expect(tA.name).toBe('Video A');
    expect(tA.clipCount).toBe(3);
    expect(tA.durationPrimary).toBe(16);
    const sc = reg.find(scenes)!;
    expect(sc.kind).toBe(StreamKind.SceneTrack);
    expect(sc.durationPrimary).toBe(3);
  });

  it('replays timeline-track events: grid order, stop-before-start ties', () => {
    const ev = reg.find(trackA)!.events;
    expect(ev.length).toBe(4);
    // [start A@0, stop A@8, start B@8, stop B@12] — clipC bypassed → no events.
    expect([ev[0].time, ev[0].kind, ev[0].clipOrdinal]).toEqual([0, 0, 0]);
    expect([ev[1].time, ev[1].kind, ev[1].clipOrdinal]).toEqual([8, 1, 0]);
    expect([ev[2].time, ev[2].kind, ev[2].clipOrdinal]).toEqual([8, 0, 1]);
    expect([ev[3].time, ev[3].kind, ev[3].clipOrdinal]).toEqual([12, 1, 1]);
    expect(ev[0].idHash48).not.toBe(ev[2].idHash48);
    expect(ev[0].idHash48).toBeLessThan(2 ** 48);
    expect(Number.isNaN(ev[0].channel)).toBe(true);
    // lower_bound cursor helper.
    expect(reg.eventLowerBound(reg.find(trackA)!, 8)).toBe(1);
    expect(reg.eventLowerBound(reg.find(trackA)!, 12.5)).toBe(4);
  });

  it('replays scene events: ordinal axis + lock-step channels, empty skipped', () => {
    const ev = reg.find(scenes)!.events;
    expect(ev.length).toBe(2);
    expect([ev[0].time, ev[0].clipOrdinal, ev[0].channel]).toEqual([0, 0, 3]);
    expect([ev[1].time, ev[1].clipOrdinal, ev[1].channel]).toEqual([1, 1, 1]);
  });

  it('classifies content streams and their seek cost', () => {
    const still = reg.find(reg.contentByClipId.get('clipA')!)!;
    expect(still.kind).toBe(StreamKind.VideoContent);
    expect(still.index).toBe(-1); // not enumerated
    expect(still.flags & StreamFlags.SeekInstant).toBeTruthy();
    const vid = reg.find(reg.contentByClipId.get('clipB')!)!;
    expect(vid.flags & StreamFlags.SeekSlow).toBeTruthy();
    expect(vid.frameCount).toBe(120);
    expect(vid.durationSec).toBe(4);
    expect(vid.anchorBeat).toBe(8);
  });

  it('mirrors resources: one ClipContent asset per content-bearing clip', () => {
    // Assertion values mirror test_streams_abi.cpp "resources: one ClipContent
    // asset per content-bearing clip".
    expect(reg.resourceByClipId.size).toBe(5);
    expect(reg.resourceByClipId.has('s3')).toBe(false);
    // A generative (streamless) clip is still forkable content.
    const g = reg.findResource(reg.resourceByClipId.get('s1')!)!;
    expect(g.flags).toBe(ResourceFlags.Forkable);
    expect(g.stream).toBe(0n);
    const rh = reg.resourceByClipId.get('clipB')!;
    expect(rh).not.toBe(reg.contentByClipId.get('clipB')); // disjoint domains
    const r = reg.findResource(rh)!;
    expect(r.kind).toBe(ResourceKind.ClipContent);
    expect(r.flags).toBe(ResourceFlags.HasStream | ResourceFlags.Forkable);
    expect(r.stream).toBe(reg.contentByClipId.get('clipB'));
    expect(r.durationSec).toBe(4);
    expect(r.ownerId).toBe('clipB');
    expect(reg.resourceRevOf(r)).toBe(reg.find(r.stream)!.eventRev);
    // Stale/foreign handles resolve to nothing; SIGNED lookups normalize.
    expect(reg.findResource(reg.contentByClipId.get('clipB')!)).toBeUndefined();
    expect(reg.findResource(BigInt.asIntN(64, rh))).toBe(r);
    // Self-scoping.
    expect(reg.resourceContentOf('clip_clipB_vid')).toBe(rh);
    expect(reg.resourceContentOf('standalone')).toBe(0n);
    // clip_at: ordinal-keyed; truly-empty clips answer 0.
    expect(reg.resourceClipAt(scenes, 1)).toBe(reg.resourceByClipId.get('s2'));
    expect(reg.resourceClipAt(scenes, 0)).toBe(reg.resourceByClipId.get('s1'));
    expect(reg.resourceClipAt(scenes, 2)).toBe(0n); // s3: truly empty
    expect(reg.resourceClipAt(scenes, 9)).toBe(0n);
    // live: the launched clip's resource; idle / non-scene → 0.
    expect(reg.resourceLive(scenes)).toBe(0n);
    reg.syncSceneLaunches({ scenes: { sceneId: 's2', launchBeat: 40 } } as any);
    expect(reg.resourceLive(scenes)).toBe(reg.resourceByClipId.get('s2'));
    expect(reg.resourceLive(trackA)).toBe(0n);
  });

  it('mirrors upcoming launches: pending wins, announces age out', () => {
    const sc = reg.find(scenes)!;
    expect(reg.nextLaunch(sc)).toBeNull();
    // Announce tee (the drain stamps ACCEPTED announces): ordinal 1 in 3 s.
    reg.noteAnnounce(sc, 1, 3.0, 1);
    let nl = reg.nextLaunch(sc)!;
    expect(nl.state).toBe(1);
    expect(nl.ordinal).toBe(1);
    expect(nl.cls).toBe(1);
    expect(nl.etaSec).toBeLessThanOrEqual(3.0);
    expect(nl.etaSec).toBeGreaterThan(2.4);
    // A pending handover WINS over the announce (the more imminent fact).
    reg.syncPendingLaunches({ scenes: { sceneId: 's2', cls: 1 } });
    nl = reg.nextLaunch(sc)!;
    expect(nl.state).toBe(2);
    expect(nl.ordinal).toBe(1);
    expect(nl.etaSec).toBe(0);
    reg.syncPendingLaunches({});
    expect(reg.nextLaunch(sc)!.state).toBe(1);
    // A silent announce expires (ANNOUNCE_STALE_SEC — backdate the stamp).
    sc.annAtMs -= 600;
    expect(reg.nextLaunch(sc)).toBeNull();
    // A fulfilled announce clears when the launch sync sees its target live.
    reg.noteAnnounce(sc, 1, 1.0, 1);
    reg.syncSceneLaunches({ scenes: { sceneId: 's2', launchBeat: 8 } } as any);
    expect(reg.nextLaunch(sc)).toBeNull();
    reg.syncSceneLaunches({});
  });

  it('resolves track-hosted instance keys to the track stream', () => {
    expect(reg.trackIdForInstanceKey('track_scenes_transport_x1')).toBe('scenes');
    expect(reg.trackIdForInstanceKey('clip_s1_dev')).toBe(null);
    expect(reg.parentOf('track_scenes_transport_x1')).toBe(scenes);
    expect(reg.parentOf('clip_clipB_vid')).toBe(trackA);  // clip keys unchanged
  });

  it('evaluates content positions identically to native (lazy + override + still)', () => {
    const vid = reg.find(reg.contentByClipId.get('clipB')!)!;
    // 'time' mode anchored at beat 8: two beats past at 120 BPM = 1 real second.
    reg.frame.posBeat = 10;
    expect(reg.pos(vid, 0)).toBeCloseTo(1.0, 9);
    // A transport-controller override beats the built-in mapping.
    reg.appliedContentSec.set('clipB', 2.75);
    expect(reg.pos(vid, 0)).toBeCloseTo(2.75, 9);
    reg.appliedContentSec.clear();
    // A still shows source second 0 for its whole span.
    const still = reg.find(reg.contentByClipId.get('clipA')!)!;
    reg.frame.posBeat = 2;
    expect(reg.pos(still, 0)).toBeCloseTo(0, 9);
  });

  it('resolves effect self-scoping from instance keys (underscore-safe)', () => {
    expect(reg.clipIdForInstanceKey('clip_clipB_transport_dev1')).toBe('clipB');
    expect(reg.clipIdForInstanceKey('track_t1_dev')).toBe(null);
    expect(reg.parentOf('clip_clipB_vid')).toBe(trackA);
    expect(reg.contentOf('clip_clipB_vid')).toBe(reg.contentByClipId.get('clipB'));
    // Unknown keys fall back to the session clock / no content.
    expect(reg.parentOf('standalone')).toBe(1n);
    expect(reg.contentOf('standalone')).toBe(0n);
  });

  it('syncs launched scenes onto the ordinal axis + re-anchors content', () => {
    const sc = reg.find(scenes)!;
    expect(Number.isNaN(reg.pos(sc, 0))).toBe(true);
    expect(reg.playing(sc)).toBe(0);
    reg.frame.playing = 1;
    reg.frame.posBeat = 42;
    reg.frame.posSec = 21;
    reg.syncSceneLaunches({ scenes: { sceneId: 's2', launchBeat: 40 } } as any);
    // s2 is grid ordinal 1, lengthBeat 4: two beats in = fraction 0.5.
    expect(reg.pos(sc, 0)).toBeCloseTo(1.5, 9);
    expect(reg.posSec(sc, 0)).toBeCloseTo(21 - 40 * 0.5, 9);
    expect(reg.playing(sc)).toBe(1);
    // The launched scene's CONTENT stream re-anchored to the launch beat.
    expect(reg.find(reg.contentByClipId.get('s2')!)!.anchorBeat).toBe(40);
    // Stop: everything reverts to idle.
    reg.syncSceneLaunches({});
    expect(Number.isNaN(reg.pos(sc, 0))).toBe(true);
  });

  it('clip refs: standard duration, follow groups, ordinal lookup (golden values)', () => {
    const sc = reg.find(scenes)!;
    expect(sc.byOrdinalClipId).toEqual(['s1', 's2', 's3']);
    // s1/s2 abut → one touching-cell follow group; s3 is EMPTY → -1.
    expect(reg.clipGroup(sc, 0)).toBe(0);
    expect(reg.clipGroup(sc, 1)).toBe(0);
    expect(reg.clipGroup(sc, 2)).toBe(-1);
    // s2 video: 60f@30 → 2 s; s1 effect-only: 4 beats @120 → 2 s.
    expect(reg.clipDuration(sc, 1)).toBeCloseTo(2, 9);
    expect(reg.clipDuration(sc, 0)).toBeCloseTo(2, 9);
    expect(Number.isNaN(reg.clipDuration(sc, 99))).toBe(true);
    const tA = reg.find(trackA)!;
    expect(reg.clipDuration(tA, tA.clipsById.get('clipB')![0])).toBeCloseTo(4, 9);
  });

  it('scene-track pos() clamps strictly below the next ordinal', () => {
    const sc = reg.find(scenes)!;
    sc.liveOrdinal = 1;
    sc.liveAnchorBeat = 10;
    sc.liveLengthBeat = 4;
    reg.frame.posBeat = 100; // long-playing: way past the grid cell
    const pos = reg.pos(sc, 0);
    expect(pos).toBeLessThan(2);
    expect(Math.floor(pos)).toBe(1); // still THIS scene's ordinal
    reg.frame.posBeat = 10;
    expect(reg.pos(sc, 0)).toBeCloseTo(1, 12);
    // Ordinal 2 is the round-to-even trap: 2 + (1 - one ulp) rounds to 3.0 —
    // the clamp margin must survive the addition.
    sc.liveOrdinal = 2;
    reg.frame.posBeat = 100;
    expect(Math.floor(reg.pos(sc, 0))).toBe(2);
  });

  it('write verbs queue with validation (seek needs TriggerOnSeek; stop needs a scene track)', () => {
    expect(reg.queueSeek(scenes, 1.0)).toBe(true);       // scene track: trigger-on-seek
    expect(reg.queueSeek(trackA, 1.0)).toBe(true);       // timeline track carries the flag too
    expect(reg.queueSeek(reg.contentByClipId.get('clipB')!, 0)).toBe(false); // content: no
    expect(reg.queueStop(scenes)).toBe(true);
    expect(reg.queueStop(trackA)).toBe(false);           // stop is scene-only
    expect(reg.pendingOps.map((o) => o.kind)).toEqual(['seek', 'seek', 'stop']);
    expect(reg.pendingOps[0].handle).toBe(scenes);
  });

  it('stop accepts BOTH content kinds — a sequence interior forks like a video', () => {
    // The fork lifecycle rides content handles, and a sequence clip's interior
    // is a content stream (kind 6) in its own right — a sequence clip on a
    // scene track is exactly what a transition crossfades. The golden doc has
    // no sequence clip (adding one would regenerate streams-golden.json), so
    // re-kind a content stream in place: the predicate is what's under test.
    const content = reg.contentByClipId.get('clipB')!;
    expect(reg.queueStop(content)).toBe(true);   // video content: fork release
    reg.find(content)!.kind = StreamKind.SequenceContent;
    expect(reg.queueStop(content)).toBe(true);   // sequence interior: same verb
    expect(reg.queueStop(trackA)).toBe(false);   // a timeline track still can't
  });

  it('announce queues like seek and carries eta (retract = t < 0)', () => {
    expect(reg.queueAnnounce(scenes, 1.0, 1.5)).toBe(true);
    expect(reg.queueAnnounce(reg.contentByClipId.get('clipB')!, 0, 1)).toBe(false); // content: no
    expect(reg.queueAnnounce(scenes, -1, 0)).toBe(true); // retract queues too
    expect(reg.pendingOps.map((o) => o.kind)).toEqual(['announce', 'announce']);
    expect(reg.pendingOps[0].eta).toBe(1.5);
    expect(reg.pendingOps[0].cls).toBe('loose');
    expect(reg.pendingOps[1].t).toBe(-1);
  });

  it('live scene state survives a static reload (doc reloads are routine)', () => {
    const sc = reg.find(scenes)!;
    reg.frame.posBeat = 42;
    reg.syncSceneLaunches({ scenes: { sceneId: 's2', launchBeat: 40 } } as any);
    expect(Math.floor(reg.pos(sc, 0))).toBe(1);
    // A doc reload rebuilds every StreamRec — the launch map must re-apply
    // (the engine's launches survive reloads; the scenes channel only ships
    // on change, so a reload would otherwise strand live positions at NaN).
    reg.loadStatic(JSON.parse(fs.readFileSync(GOLDEN, 'utf8')), secondsAt);
    const sc2 = reg.find(scenes)!;
    expect(Math.floor(reg.pos(sc2, 0))).toBe(1);
    expect(reg.find(reg.contentByClipId.get('s2')!)!.anchorBeat).toBe(40);
  });

  it('content event timeline: analytic looped/ended, elapsed axis, growth (lock-step)', () => {
    // clipB: 'time' loop, full 4 s slice, speed 1, anchored at beat 8
    // (anchorSec 4 shipped). Mirrors test_streams_abi's content-event case.
    const vid = reg.find(reg.contentByClipId.get('clipB')!)!;
    expect(vid.flags & StreamFlags.HasEvents).toBeTruthy();
    expect(vid.eventRev).toBe(7);
    expect(vid.anchorSec).toBeCloseTo(4, 9);

    reg.frame.posBeat = 8;
    reg.frame.posSec = 4; // elapsed 0
    expect(reg.elapsed(vid, 0)).toBeCloseTo(0, 9);
    expect(reg.contentEventCount(vid, 0)).toBe(CONTENT_EVENT_HORIZON);
    const e0 = reg.contentEventAt(vid, 0);
    expect(e0.time).toBeCloseTo(4, 9);
    expect(e0.kind).toBe(2);
    expect(e0.clipOrdinal).toBe(1);

    expect(reg.contentEventCount(vid, 9.5)).toBe(2 + CONTENT_EVENT_HORIZON);
    expect(reg.contentEventAt(vid, 1).time).toBeCloseTo(8, 9);
    expect(reg.contentEventAt(vid, 1).clipOrdinal).toBe(2);
    // BOUNDARY-EXACT: elapsed exactly on a boundary counts it as past.
    expect(reg.contentEventCount(vid, 8.0)).toBe(2 + CONTENT_EVENT_HORIZON);
    reg.frame.posSec = 12; // elapsed 8 — lower_bound reads "now" itself
    expect(reg.contentEventLowerBound(vid, 8.0)).toBe(1);
    reg.frame.posSec = 4;

    // s2 (no loop config → 'time' default): full 2 s slice, period 2.
    const s2c = reg.find(reg.contentByClipId.get('s2')!)!;
    expect(reg.contentEventAt(s2c, 0).time).toBeCloseTo(2, 9);

    // One-shot: a single 'ended' EXACTLY at standardClipDurationSec.
    const one = { ...vid, loop: { ...(vid.loop as any), mode: 'one-shot', endSec: 3, speed: 2 } };
    expect(reg.contentEventCount(one, 100)).toBe(1);
    expect(reg.contentEventAt(one, 0).kind).toBe(3);
    expect(reg.contentEventAt(one, 0).time).toBeCloseTo(1.5, 9);

    // playStartSec pre-roll / reverse / pingpong (clip_time.h semantics).
    const pre = { ...vid, loop: { ...(vid.loop as any), playStartSec: 1 } };
    expect(reg.contentEventAt(pre, 0).time).toBeCloseTo(3, 9);
    expect(reg.contentEventAt(pre, 1).time).toBeCloseTo(7, 9);
    const rev = { ...pre, loop: { ...(pre.loop as any), direction: 'reverse' } };
    expect(reg.contentEventAt(rev, 0).time).toBeCloseTo(1, 9);
    const pp = { ...pre, loop: { ...(pre.loop as any), pingpong: true } };
    expect(reg.contentEventAt(pp, 1).time).toBeCloseTo(7, 9);

    // Beat-sync: boundaries in BEATS (the elapsed axis for beat-sync clips).
    const bs = { ...vid, loop: { ...(vid.loop as any), mode: 'beat-sync', syncBeats: 4 } };
    reg.frame.posBeat = 14; // 6 beats past anchor 8
    expect(reg.elapsed(bs, 0)).toBeCloseTo(6, 9);
    expect(reg.contentEventAt(bs, 0).time).toBeCloseTo(4, 9);
    expect(reg.contentEventCount(bs, 6)).toBe(1 + CONTENT_EVENT_HORIZON);

    // Random: NO boundaries — readers fall back to clip_duration.
    const rnd = { ...vid, loop: { ...(vid.loop as any), mode: 'random' } };
    expect(reg.contentEventCount(rnd, 100)).toBe(0);
  });

  it('declared future replaces the analytics; foldDecl quantizes + appends', () => {
    const vid = reg.find(reg.contentByClipId.get('clipB')!)!;
    reg.frame.posBeat = 8;
    reg.frame.posSec = 4; // elapsed 0
    const rev0 = vid.eventRev;
    reg.foldDecl('clipB', 3.5, 0);
    expect(vid.declared).toBe(true);
    expect(vid.declNextEnd).toBeCloseTo(3.5, 9);
    expect(vid.eventRev).toBeGreaterThan(rev0);
    expect(reg.contentEventCount(vid, 0)).toBe(1);
    expect(reg.contentEventAt(vid, 0).kind).toBe(3);
    // Sub-10ms jitter does NOT churn the rev (quantized absolute end).
    const rev1 = vid.eventRev;
    reg.foldDecl('clipB', 3.504, 0);
    expect(vid.eventRev).toBe(rev1);
    // Integer loop-count increments append 'looped' edges at observed elapsed.
    reg.frame.posSec = 6; // elapsed 2
    reg.foldDecl('clipB', 1.5, 2);
    expect(vid.dynEvents.length).toBe(2);
    expect(vid.dynEvents[1]).toMatchObject({ kind: 2, clipOrdinal: 2 });
    expect(vid.dynEvents[1].time).toBeCloseTo(2, 9);
    // Controller vanished → back to the analytics, rev bumped.
    const rev2 = vid.eventRev;
    reg.pruneDecls(new Set());
    expect(vid.declared).toBe(false);
    expect(vid.eventRev).toBeGreaterThan(rev2);
    expect(reg.contentEventCount(vid, 0)).toBe(CONTENT_EVENT_HORIZON);
  });

  it('a scene (re)launch re-anchors content with SHIPPED seconds + bumps revs', () => {
    const sc = reg.find(scenes)!;
    const content = reg.find(reg.contentByClipId.get('s2')!)!;
    const revT0 = sc.eventRev;
    const revC0 = content.eventRev;
    reg.syncSceneLaunches({ scenes: { sceneId: 's2', launchBeat: 40, launchSec: 20.25 } } as any);
    expect(content.anchorBeat).toBe(40);
    expect(content.anchorSec).toBe(20.25); // the shipped double, NOT secondsAt(40)
    expect(sc.eventRev).toBeGreaterThan(revT0);
    expect(content.eventRev).toBeGreaterThan(revC0);
    // The SAME map again (per-frame re-sync) must NOT bump.
    const revT1 = sc.eventRev;
    reg.syncSceneLaunches({ scenes: { sceneId: 's2', launchBeat: 40, launchSec: 20.25 } } as any);
    expect(sc.eventRev).toBe(revT1);
    // Stop bumps both.
    reg.syncSceneLaunches({});
    expect(sc.eventRev).toBeGreaterThan(revT1);
  });

  it('reports loop regions per kind', () => {
    // Timeline loop brace rides the frame sample.
    reg.frame.loopEnabled = 1;
    reg.frame.loopStartBeat = 4;
    reg.frame.loopEndBeat = 12;
    expect(reg.loopRegion(reg.find(trackA)!)).toEqual([4, 12]);
    reg.frame.loopEnabled = 0;
    expect(reg.loopRegion(reg.find(trackA)!)).toBe(null);
    // A 'time'-mode content stream exposes its source slice.
    const vid = reg.find(reg.contentByClipId.get('clipB')!)!;
    expect(reg.loopRegion(vid)).toEqual([0, 4]);
    // Scene tracks and clocks have none.
    expect(reg.loopRegion(reg.find(scenes)!)).toBe(null);
    expect(reg.loopRegion(reg.streams[0])).toBe(null);
  });
});
